export const uiTokens = {
  surfaceMuted: "var(--ui-surface-muted)",
  borderStrong: "var(--ui-border-strong)",
  textInverse: "var(--ui-text-inverse)",
  actionPrimary: "var(--ui-action-primary)",
  actionPrimaryHover: "var(--ui-action-primary-hover)",
  dangerFg: "var(--ui-danger-fg)",
  dangerBg: "var(--ui-danger-bg)",
  dangerBorder: "var(--ui-danger-border)",
  successFg: "var(--ui-success-fg)",
  successBg: "var(--ui-success-bg)",
  successBorder: "var(--ui-success-border)",
  warningFg: "var(--ui-warning-fg)",
  warningBg: "var(--ui-warning-bg)",
  warningBorder: "var(--ui-warning-border)",
  tableHeaderBg: "var(--ui-table-header-bg)",
  tableHeaderFg: "var(--ui-table-header-fg)",
  fontMono: "var(--ui-font-mono)",
  radiusPill: "var(--ui-radius-pill)",
  sectionPx: "var(--ui-section-px)",
  sectionPy: "var(--ui-section-py)",
  pagePadding: "var(--ui-page-padding)",
  pageMax: "var(--ui-page-max)",
  canvas: "var(--ui-canvas)",
  surface: "var(--ui-surface)",
  surfaceRaised: "var(--ui-surface-raised)",
  borderSubtle: "var(--ui-border-subtle)",
  borderDefault: "var(--ui-border-default)",
  borderFocus: "var(--ui-border-focus)",
  textPrimary: "var(--ui-text-primary)",
  textSecondary: "var(--ui-text-secondary)",
  textTertiary: "var(--ui-text-tertiary)",
  radiusCard: "var(--ui-radius-card)",
  radiusControl: "var(--ui-radius-control)",
  radiusAction: "var(--ui-radius-action)",
  sectionGap: "var(--ui-section-gap)",
  shadowElevated: "var(--ui-shadow-elevated)",
} as const;

export const dialogWidths = {
  sm: "var(--ui-dialog-sm)",
  md: "var(--ui-dialog-md)",
  lg: "var(--ui-dialog-lg)",
  xl: "var(--ui-dialog-xl)",
  full: "var(--ui-dialog-full)",
} as const;
