import assert from "node:assert/strict"; import { describe,it } from "node:test";
import { assertSkuKind, assertSkuRelations, assertSkuStatusTransition, normalizeSkuMedia, optionalNonNegativeDecimal, optionalPositiveDecimal } from "./sku-rules";
const live = (id:string) => ({id,deletedAt:null});
describe("SKU rules",()=>{
 it("locks kind and status graph",()=>{ assert.throws(()=>assertSkuKind("SERVICE"),{code:"SKU_KIND_INVALID"}); assert.doesNotThrow(()=>assertSkuStatusTransition("DRAFT","ACTIVE")); assert.throws(()=>assertSkuStatusTransition("DRAFT","DISCONTINUED"),{code:"SKU_STATUS_TRANSITION_INVALID"}); });
 it("keeps exact decimal constraints",()=>{ assert.equal(optionalNonNegativeDecimal("0.5000","X"),"0.5"); assert.throws(()=>optionalPositiveDecimal("0","X"),{code:"X"}); assert.throws(()=>optionalNonNegativeDecimal("-1","X"),{code:"X"}); });
 it("allows incomplete DRAFT but enforces unit conversion and ACTIVE readiness",()=>{ const base={brand:null,category:null,baseUnit:live("u"),purchaseUnit:null,dimensionUnit:null,skuPrices:[] as {unitId:string}[]}; assert.doesNotThrow(()=>assertSkuRelations({status:"DRAFT",baseUnitId:"u",purchaseUnitId:null,dimensionUnitId:null,categoryId:null,brandId:null,conversion:null,relations:base})); assert.throws(()=>assertSkuRelations({status:"ACTIVE",baseUnitId:"u",purchaseUnitId:null,dimensionUnitId:null,categoryId:null,brandId:null,conversion:null,relations:base}),{code:"SKU_ACTIVE_CATEGORY_REQUIRED"}); assert.throws(()=>assertSkuRelations({status:"ACTIVE",baseUnitId:"u",purchaseUnitId:null,dimensionUnitId:null,categoryId:"cat",brandId:null,conversion:null,relations:{...base,category:{id:"cat",kind:"PRODUCT",deletedAt:null}}}),{code:"SKU_ACTIVE_PRICE_REQUIRED"}); assert.doesNotThrow(()=>assertSkuRelations({status:"ACTIVE",baseUnitId:"u",purchaseUnitId:null,dimensionUnitId:null,categoryId:"cat",brandId:null,conversion:null,relations:{...base,category:{id:"cat",kind:"PRODUCT",deletedAt:null},skuPrices:[{unitId:"u"},{unitId:"u"}]}})); assert.throws(()=>assertSkuRelations({status:"DRAFT",baseUnitId:"u",purchaseUnitId:"p",dimensionUnitId:null,categoryId:null,brandId:null,conversion:null,relations:{...base,purchaseUnit:live("p")}}),{code:"SKU_CONVERSION_REQUIRED"}); });
 it("fails unit edits that would desynchronize any supplier price",()=>{ assert.throws(()=>assertSkuRelations({status:"DRAFT",baseUnitId:"u",purchaseUnitId:"p",dimensionUnitId:null,categoryId:null,brandId:null,conversion:"1" as never,relations:{brand:null,category:null,baseUnit:live("u"),purchaseUnit:live("p"),dimensionUnit:null,skuPrices:[{unitId:"u"},{unitId:"p"}]}}),{code:"SKU_PRICE_UNIT_MISMATCH"}); });
 it("validates owned media",()=>{ assert.throws(()=>normalizeSkuMedia([{url:""}]),{code:"SKU_MEDIA_URL_REQUIRED"}); assert.throws(()=>normalizeSkuMedia([{url:"a"},{url:"a"}]),{code:"SKU_MEDIA_URL_DUPLICATE"}); });
});
