import Link from "next/link";
import { BriefcaseBusiness } from "lucide-react";
import { businessTypeService } from "@masterdata/infrastructure/runtime";
import { requireMasterDataRequestContext } from "@masterdata/infrastructure/request-context";
import { Badge, Button, buttonClasses, DataTable, EmptyState, PageHeader, PageShell, TableBody, TableCell, TableCellContent, TableHead, TableHeader, TableRow } from "@/platform/ui_engine";
import { SortableTableHead } from "../../sortable-table-head";
import { deleteBusinessTypeAction, restoreBusinessTypeAction } from "./actions";
export default async function BusinessTypesPage({ searchParams }: { searchParams: Promise<Record<string,string|string[]|undefined>> }) {
  const sp=await searchParams, showDeleted=sp.deleted==="1", sort=typeof sp.sort==="string"?sp.sort:"code", direction=sp.dir==="desc"?-1:1;
  const rows=(await businessTypeService.list((await requireMasterDataRequestContext()),showDeleted)).toSorted((a,b)=>direction*String(sort==="label"?a.label:sort==="order"?a.sortOrder:sort==="status"?Boolean(a.deletedAt):a.code).localeCompare(String(sort==="label"?b.label:sort==="order"?b.sortOrder:sort==="status"?Boolean(b.deletedAt):b.code),"id-ID",{numeric:true}));
  return <PageShell><PageHeader eyebrow="General settings" title="Business Types" description="Editable commercial classifications; they never grant an operational role." actions={<Link href="/masterdata/settings/business-types/new" className={buttonClasses("primary")}>New business type</Link>}/><Link href={`/masterdata/settings/business-types${showDeleted?"":"?deleted=1"}`} className={buttonClasses("secondary")}>{showDeleted?"Hide archived":"Show archived"}</Link><DataTable><TableHeader><TableRow><SortableTableHead column="code">Code</SortableTableHead><SortableTableHead column="label">Label</SortableTableHead><SortableTableHead column="order">Sort</SortableTableHead><SortableTableHead column="status">Status</SortableTableHead><TableHead aria-label="Actions"/></TableRow></TableHeader><TableBody>{rows.length===0?<TableRow><TableCell colSpan={5}><EmptyState icon={BriefcaseBusiness} title="No business types"/></TableCell></TableRow>:rows.map(row=><TableRow key={row.id}><TableCell><TableCellContent primary={row.code} secondary={row.description??undefined}/></TableCell><TableCell>{row.label}</TableCell><TableCell>{row.sortOrder}</TableCell><TableCell><Badge tone={row.deletedAt?"warning":"success"}>{row.deletedAt?"Archived":"Active"}</Badge></TableCell><TableCell>{row.deletedAt?<form action={restoreBusinessTypeAction.bind(null,row.id)}><Button type="submit" variant="ghost">Restore</Button></form>:<div className="flex flex-wrap items-center gap-2"><Link href={`/masterdata/settings/business-types/${row.id}/edit`} className={buttonClasses("ghost")}>Edit</Link><form action={deleteBusinessTypeAction.bind(null,row.id)}><Button type="submit" variant="danger">Archive</Button></form></div>}</TableCell></TableRow>)}</TableBody></DataTable></PageShell>;
}
