"use client";

import { useState, useTransition } from "react";
import { Archive, RotateCcw, Trash2 } from "lucide-react";
import { Button, ConfirmDialog, DataTable, Dialog, EmptyState, Field, FormActions, Input, SearchField, SectionCard, Select, Spinner, StatusBadge, TableCell, TableCellContent, TableHead, TableHeader, TableRow, TableToolbar, Tabs } from "@/platform/ui_engine";
import { archivePriceAction, requestPriceDeletionAction, restorePriceAction, savePriceAction } from "./actions";

type MaterialRow = { id: string; sku: { name: string; code: string | null }; supplier_vendor: { name: string }; amount: string; currency: string; unit: { code: string }; deleted_at: Date | null };
type WorkRow = { id: string; name: string; category: { name: string }; vendor: { name: string }; amount: string; currency: string; unit: { code: string }; deleted_at: Date | null };
type Kind = "material" | "material-labor" | "labor";
type Target = { kind: Kind; id: string; name: string };

export function PricingDirectory({ materialPrices, materialLaborPrices, laborPrices, canManageMaterial, canManageWork, canReadMaterial, canReadWork, skus, vendors, units, workCategories }: { materialPrices: MaterialRow[]; materialLaborPrices: WorkRow[]; laborPrices: WorkRow[]; canManageMaterial: boolean; canManageWork: boolean; canReadMaterial: boolean; canReadWork: boolean; skus: Array<{ id: string; name: string; code: string | null }>; vendors: Array<{ id: string; name: string }>; units: Array<{ id: string; code: string; name: string }>; workCategories: Array<{ id: string; name: string }> }) {
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("ACTIVE");
  const [archive, setArchive] = useState<Target | null>(null);
  const [restore, setRestore] = useState<Target | null>(null);
  const [deletion, setDeletion] = useState<Target | null>(null);
  const [reason, setReason] = useState("");
  const [pendingId, setPendingId] = useState<string | null>(null);
  const [createOpen, setCreateOpen] = useState(false);
  const [createKind, setCreateKind] = useState<Kind>("material");
  const [formError, setFormError] = useState<string | null>(null);
  const [, startTransition] = useTransition();
  const matches = (text: string, archived: boolean) => (status === "ALL" || (status === "ARCHIVED") === archived) && text.toLowerCase().includes(query.toLowerCase());
  const run = (id: string, fn: () => Promise<unknown>) => { setPendingId(id); startTransition(async () => { try { await fn(); } finally { setPendingId(null); } }); };
  const tools = <TableToolbar><div className="flex flex-wrap items-center gap-3"><SearchField value={query} onChange={(event) => setQuery(event.target.value)} onClear={() => setQuery("")} placeholder="Search pricing..." /><Select value={status} onChange={(event) => setStatus(event.target.value)} className="w-36"><option value="ACTIVE">Active</option><option value="ARCHIVED">Archived</option><option value="ALL">All status</option></Select></div></TableToolbar>;
  const actions = (row: { id: string; deleted_at: Date | null }, target: Target, canManage: boolean) => !canManage ? null : <TableCell align="end"><div className="flex items-center justify-end gap-1">{pendingId === row.id && <Spinner />}{!row.deleted_at ? <Button size="sm" variant="ghost" title="Archive" disabled={pendingId === row.id} onClick={() => setArchive(target)}><Archive size={15} /></Button> : <><Button size="sm" variant="ghost" title="Restore" disabled={pendingId === row.id} onClick={() => setRestore(target)}><RotateCcw size={15} /></Button><Button size="sm" variant="danger" title="Request deletion" disabled={pendingId === row.id} onClick={() => setDeletion(target)}><Trash2 size={15} /></Button></>}</div></TableCell>;
  const material = materialPrices.filter((row) => matches(`${row.sku.name} ${row.sku.code ?? ""} ${row.supplier_vendor.name}`, Boolean(row.deleted_at)));
  const work = (rows: WorkRow[], kind: Kind, canManage: boolean, title: string) => { const filtered = rows.filter((row) => matches(`${row.name} ${row.category.name} ${row.vendor.name}`, Boolean(row.deleted_at))); return <div className="grid gap-4">{tools}{filtered.length === 0 ? <EmptyState title={title} description={query ? "No prices match this search." : "No pricing records yet."} /> : <DataTable minWidth={760}><TableHeader><TableRow><TableHead>Name</TableHead><TableHead>Category</TableHead><TableHead>Vendor</TableHead><TableHead align="end">Price</TableHead><TableHead>Unit</TableHead><TableHead>Status</TableHead>{canManage && <TableHead align="end">Actions</TableHead>}</TableRow></TableHeader><tbody>{filtered.map((row) => { const archived = Boolean(row.deleted_at); return <TableRow key={row.id}><TableCell><TableCellContent primary={<span className="font-semibold">{row.name}</span>} /></TableCell><TableCell>{row.category.name}</TableCell><TableCell>{row.vendor.name}</TableCell><TableCell align="end">{row.currency} {row.amount}</TableCell><TableCell><span className="font-mono text-xs">{row.unit.code}</span></TableCell><TableCell><StatusBadge tone={archived ? "neutral" : "success"}>{archived ? "Archived" : "Active"}</StatusBadge></TableCell>{actions(row, { kind, id: row.id, name: row.name }, canManage)}</TableRow>; })}</tbody></DataTable>}</div>; };

  const createDialog = createOpen ? <Dialog open onOpenChange={setCreateOpen} title="Create price" description="Choose only active and eligible catalog references."><form className="grid gap-4" onSubmit={async (event) => { event.preventDefault(); setFormError(null); const result = await savePriceAction(createKind, new FormData(event.currentTarget)); if (result.ok) setCreateOpen(false); else setFormError(result.error.safeMessage); }}>
    {formError ? <div role="alert" className="text-sm text-danger">{formError}</div> : null}
    {createKind === "material" ? <><Field label="SKU" required><Select name="skuId" required><option value="">Select SKU</option>{skus.map((sku) => <option key={sku.id} value={sku.id}>{sku.name}{sku.code ? ` (${sku.code})` : ""}</option>)}</Select></Field><Field label="Supplier vendor" required><Select name="vendorId" required><option value="">Select vendor</option>{vendors.map((vendor) => <option key={vendor.id} value={vendor.id}>{vendor.name}</option>)}</Select></Field></> : <><Field label="Name" required><Input name="name" required /></Field><Field label="WORK category" required><Select name="categoryId" required><option value="">Select category</option>{workCategories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</Select></Field><Field label="Vendor" required><Select name="vendorId" required><option value="">Select vendor</option>{vendors.map((vendor) => <option key={vendor.id} value={vendor.id}>{vendor.name}</option>)}</Select></Field><Field label="Unit" required><Select name="unitId" required><option value="">Select unit</option>{units.map((unit) => <option key={unit.id} value={unit.id}>{unit.name} ({unit.code})</option>)}</Select></Field>{createKind === "material-labor" ? <Field label="Scope note"><Input name="scopeNote" /></Field> : null}</>}
    <Field label="Amount" required><Input name="amount" inputMode="decimal" required /></Field><Field label="Currency" required><Input name="currency" defaultValue="IDR" maxLength={3} required onInput={(event) => { event.currentTarget.value = event.currentTarget.value.toUpperCase(); }} /></Field><Field label="Notes"><Input name="notes" /></Field><FormActions><Button type="button" variant="ghost" onClick={() => setCreateOpen(false)}>Cancel</Button><Button type="submit" variant="primary">Create price</Button></FormActions>
  </form></Dialog> : null;
  const addButton = (kind: Kind, allowed: boolean) => allowed ? <Button variant="primary" onClick={() => { setCreateKind(kind); setCreateOpen(true); }}><span>New price</span></Button> : null;
  return <SectionCard>{createDialog}<div className="flex justify-end gap-2">{addButton("material", canManageMaterial)}{addButton("material-labor", canManageWork)}{addButton("labor", canManageWork)}</div><Tabs items={[
    { value: "material", label: `Material Prices (${materialPrices.length})`, disabled: !canReadMaterial, content: <div className="grid gap-4">{tools}{material.length === 0 ? <EmptyState title="No material prices" description={query ? "No prices match this search." : "Material prices are created as part of the SKU flow."} /> : <DataTable minWidth={720}><TableHeader><TableRow><TableHead>SKU</TableHead><TableHead>Supplier</TableHead><TableHead align="end">Price</TableHead><TableHead>Unit</TableHead><TableHead>Status</TableHead>{canManageMaterial && <TableHead align="end">Actions</TableHead>}</TableRow></TableHeader><tbody>{material.map((row) => { const archived = Boolean(row.deleted_at); return <TableRow key={row.id}><TableCell><TableCellContent primary={<span className="font-semibold">{row.sku.name}</span>} secondary={row.sku.code ? <span className="font-mono text-xs">{row.sku.code}</span> : undefined} /></TableCell><TableCell>{row.supplier_vendor.name}</TableCell><TableCell align="end">{row.currency} {row.amount}</TableCell><TableCell><span className="font-mono text-xs">{row.unit.code}</span></TableCell><TableCell><StatusBadge tone={archived ? "neutral" : "success"}>{archived ? "Archived" : "Active"}</StatusBadge></TableCell>{actions(row, { kind: "material", id: row.id, name: `${row.sku.name} / ${row.supplier_vendor.name}` }, canManageMaterial)}</TableRow>; })}</tbody></DataTable>}</div> },
    { value: "material-labor", label: `Material + Labor (${materialLaborPrices.length})`, disabled: !canReadWork, content: work(materialLaborPrices, "material-labor", canManageWork, "No material + labor prices") },
    { value: "labor", label: `Labor Only (${laborPrices.length})`, disabled: !canReadWork, content: work(laborPrices, "labor", canManageWork, "No labor-only prices") },
  ]} />
  {archive && <ConfirmDialog open onOpenChange={(open) => !open && setArchive(null)} title={`Archive ${archive.name}?`} description="It will be removed from active pricing and pickers." confirmLabel="Archive" tone="danger" onConfirm={() => { const value = archive; setArchive(null); run(value.id, () => archivePriceAction(value.kind, value.id)); }} />}
  {restore && <ConfirmDialog open onOpenChange={(open) => !open && setRestore(null)} title={`Restore ${restore.name}?`} description="Required references will be validated before restoring it." confirmLabel="Restore" onConfirm={() => { const value = restore; setRestore(null); run(value.id, () => restorePriceAction(value.kind, value.id)); }} />}
  {deletion && <Dialog open onOpenChange={(open) => !open && setDeletion(null)} title="Request permanent deletion" description="The archived record remains until a deletion approver accepts this request."><div className="grid gap-4"><Field label="Reason"><Input value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Optional context for the approver" /></Field><FormActions><Button variant="ghost" onClick={() => setDeletion(null)}>Cancel</Button><Button variant="danger" onClick={() => { const value = deletion; const note = reason; setDeletion(null); setReason(""); run(value.id, () => requestPriceDeletionAction(value.kind, value.id, note)); }}>Submit request</Button></FormActions></div></Dialog>}
  </SectionCard>;
}
