"use client";

import { useState, useTransition, type FormEvent } from "react";
import { Archive, Pencil, RotateCcw, Trash2 } from "lucide-react";
import { Button, ConfirmDialog, DataTable, Dialog, EmptyState, Field, FormActions, Input, SearchField, SectionCard, Select, Spinner, StatusBadge, TableCell, TableCellContent, TableHead, TableHeader, TableRow, TableToolbar, Tabs } from "@/platform/ui_engine";
import { archivePriceAction, requestPriceDeletionAction, restorePriceAction, savePriceAction } from "./actions";

type Kind = "material" | "material-labor" | "labor";
type MaterialRow = { id: string; sku: { id: string; name: string; code: string | null }; supplier_vendor: { id: string; name: string }; amount: string; currency: string; unit: { id: string; code: string; name: string }; notes: string | null; deleted_at: Date | null };
type WorkRow = { id: string; name: string; category: { id: string; name: string }; vendor: { id: string; name: string }; amount: string; currency: string; unit: { id: string; code: string; name: string }; scope_note?: string | null; notes: string | null; deleted_at: Date | null };
type Target = { kind: Kind; id: string; name: string };
type Editor = { kind: Kind; row?: MaterialRow | WorkRow };
type Ref = { id: string; name: string };

export function PricingDirectory(props: { materialPrices: MaterialRow[]; materialLaborPrices: WorkRow[]; laborPrices: WorkRow[]; canManageMaterial: boolean; canManageWork: boolean; canReadMaterial: boolean; canReadWork: boolean; skus: Array<{ id: string; name: string; code: string | null }>; vendors: Ref[]; units: Array<Ref & { code: string }>; workCategories: Ref[] }) {
  const [query, setQuery] = useState(""); const [status, setStatus] = useState("ACTIVE"); const [editor, setEditor] = useState<Editor | null>(null); const [formError, setFormError] = useState<string | null>(null);
  const [archive, setArchive] = useState<Target | null>(null); const [restore, setRestore] = useState<Target | null>(null); const [deletion, setDeletion] = useState<Target | null>(null); const [reason, setReason] = useState(""); const [pendingId, setPendingId] = useState<string | null>(null); const [, startTransition] = useTransition();
  const matches = (text: string, archived: boolean) => (status === "ALL" || (status === "ARCHIVED") === archived) && text.toLowerCase().includes(query.toLowerCase());
  const run = (id: string, fn: () => Promise<unknown>) => { setPendingId(id); startTransition(async () => { try { await fn(); } finally { setPendingId(null); } }); };
  const closeEditor = () => { setEditor(null); setFormError(null); };
  const toolbar = <TableToolbar><div className="flex flex-wrap items-center gap-3"><SearchField value={query} onChange={(event) => setQuery(event.target.value)} onClear={() => setQuery("")} placeholder="Search pricing..." /><Select value={status} onChange={(event) => setStatus(event.target.value)} className="w-36"><option value="ACTIVE">Active</option><option value="ARCHIVED">Archived</option><option value="ALL">All status</option></Select></div></TableToolbar>;
  const actions = (row: { id: string; deleted_at: Date | null }, target: Target, canManage: boolean, edit: () => void) => !canManage ? null : <TableCell align="end"><div className="flex items-center justify-end gap-1">{pendingId === row.id && <Spinner />}{!row.deleted_at ? <><Button size="sm" variant="ghost" title="Edit" onClick={edit}><Pencil size={15} /></Button><Button size="sm" variant="ghost" title="Archive" onClick={() => setArchive(target)}><Archive size={15} /></Button></> : <><Button size="sm" variant="ghost" title="Restore" onClick={() => setRestore(target)}><RotateCcw size={15} /></Button><Button size="sm" variant="danger" title="Request deletion" onClick={() => setDeletion(target)}><Trash2 size={15} /></Button></>}</div></TableCell>;
  const material = props.materialPrices.filter((row) => matches(`${row.sku.name} ${row.sku.code ?? ""} ${row.supplier_vendor.name}`, Boolean(row.deleted_at)));
  const workTable = (rows: WorkRow[], kind: Kind, canManage: boolean, title: string) => { const filtered = rows.filter((row) => matches(`${row.name} ${row.category.name} ${row.vendor.name}`, Boolean(row.deleted_at))); return <div className="grid gap-4">{toolbar}{filtered.length === 0 ? <EmptyState title={title} description={query ? "No prices match this search." : "No pricing records yet."} /> : <DataTable minWidth={760}><TableHeader><TableRow><TableHead>Name</TableHead><TableHead>Category</TableHead><TableHead>Vendor</TableHead><TableHead align="end">Price</TableHead><TableHead>Unit</TableHead><TableHead>Status</TableHead>{canManage && <TableHead align="end">Actions</TableHead>}</TableRow></TableHeader><tbody>{filtered.map((row) => <TableRow key={row.id}><TableCell><TableCellContent primary={<span className="font-semibold">{row.name}</span>} /></TableCell><TableCell>{row.category.name}</TableCell><TableCell>{row.vendor.name}</TableCell><TableCell align="end">{row.currency} {row.amount}</TableCell><TableCell><span className="font-mono text-xs">{row.unit.code}</span></TableCell><TableCell><StatusBadge tone={row.deleted_at ? "neutral" : "success"}>{row.deleted_at ? "Archived" : "Active"}</StatusBadge></TableCell>{actions(row, { kind, id: row.id, name: row.name }, canManage, () => setEditor({ kind, row }))}</TableRow>)}</tbody></DataTable>}</div>; };
  return <SectionCard>
    {editor && <PriceEditor editor={editor} refs={props} error={formError} onCancel={closeEditor} onSubmit={async (event) => { event.preventDefault(); setFormError(null); const result = await savePriceAction(editor.kind, new FormData(event.currentTarget)); if (result.ok) closeEditor(); else setFormError(result.error.safeMessage); }} />}
    <div className="flex flex-wrap justify-end gap-2">{props.canManageMaterial && <Button variant="primary" onClick={() => setEditor({ kind: "material" })}>New material price</Button>}{props.canManageWork && <Button variant="primary" onClick={() => setEditor({ kind: "material-labor" })}>New work price</Button>}{props.canManageWork && <Button variant="primary" onClick={() => setEditor({ kind: "labor" })}>New labor price</Button>}</div>
    <Tabs items={[
      { value: "material", label: `Material Prices (${props.materialPrices.length})`, disabled: !props.canReadMaterial, content: <div className="grid gap-4">{toolbar}{material.length === 0 ? <EmptyState title="No material prices" description={query ? "No prices match this search." : "Create a material price for an active SKU and eligible vendor."} /> : <DataTable minWidth={720}><TableHeader><TableRow><TableHead>SKU</TableHead><TableHead>Supplier</TableHead><TableHead align="end">Price</TableHead><TableHead>Unit</TableHead><TableHead>Status</TableHead>{props.canManageMaterial && <TableHead align="end">Actions</TableHead>}</TableRow></TableHeader><tbody>{material.map((row) => <TableRow key={row.id}><TableCell><TableCellContent primary={<span className="font-semibold">{row.sku.name}</span>} secondary={row.sku.code ? <span className="font-mono text-xs">{row.sku.code}</span> : undefined} /></TableCell><TableCell>{row.supplier_vendor.name}</TableCell><TableCell align="end">{row.currency} {row.amount}</TableCell><TableCell><span className="font-mono text-xs">{row.unit.code}</span></TableCell><TableCell><StatusBadge tone={row.deleted_at ? "neutral" : "success"}>{row.deleted_at ? "Archived" : "Active"}</StatusBadge></TableCell>{actions(row, { kind: "material", id: row.id, name: `${row.sku.name} / ${row.supplier_vendor.name}` }, props.canManageMaterial, () => setEditor({ kind: "material", row }))}</TableRow>)}</tbody></DataTable>}</div> },
      { value: "material-labor", label: `Material + Labor (${props.materialLaborPrices.length})`, disabled: !props.canReadWork, content: workTable(props.materialLaborPrices, "material-labor", props.canManageWork, "No material + labor prices") },
      { value: "labor", label: `Labor Only (${props.laborPrices.length})`, disabled: !props.canReadWork, content: workTable(props.laborPrices, "labor", props.canManageWork, "No labor-only prices") },
    ]} />
    {archive && <ConfirmDialog open onOpenChange={(open) => !open && setArchive(null)} title={`Archive ${archive.name}?`} description="It will be removed from active pricing and pickers." confirmLabel="Archive" tone="danger" onConfirm={() => { const value = archive; setArchive(null); run(value.id, () => archivePriceAction(value.kind, value.id)); }} />}
    {restore && <ConfirmDialog open onOpenChange={(open) => !open && setRestore(null)} title={`Restore ${restore.name}?`} description="Required references will be validated before restoring it." confirmLabel="Restore" onConfirm={() => { const value = restore; setRestore(null); run(value.id, () => restorePriceAction(value.kind, value.id)); }} />}
    {deletion && <Dialog open onOpenChange={(open) => !open && setDeletion(null)} title="Request permanent deletion" description="The archived record remains until a deletion approver accepts this request."><div className="grid gap-4"><Field label="Reason"><Input value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Optional context for the approver" /></Field><FormActions><Button variant="ghost" onClick={() => setDeletion(null)}>Cancel</Button><Button variant="danger" onClick={() => { const value = deletion; const note = reason; setDeletion(null); setReason(""); run(value.id, () => requestPriceDeletionAction(value.kind, value.id, note)); }}>Submit request</Button></FormActions></div></Dialog>}
  </SectionCard>;
}

function PriceEditor({ editor, refs, error, onCancel, onSubmit }: { editor: Editor; refs: { skus: Array<{ id: string; name: string; code: string | null }>; vendors: Ref[]; units: Array<Ref & { code: string }>; workCategories: Ref[] }; error: string | null; onCancel: () => void; onSubmit: (event: FormEvent<HTMLFormElement>) => Promise<void> }) {
  const edit = Boolean(editor.row); const material = editor.kind === "material"; const row = editor.row; const materialRow = material && row ? row as MaterialRow : undefined; const workRow = !material && row ? row as WorkRow : undefined;
  return <Dialog open onOpenChange={(open) => !open && onCancel()} title={`${edit ? "Edit" : "Create"} ${material ? "material price" : "price"}`} description={material && edit ? "SKU and supplier identity are read-only." : "Choose only active and eligible catalog references."}><form className="grid gap-4" onSubmit={onSubmit}>
    {edit && <input type="hidden" name="id" value={row!.id} />}{error && <div role="alert" className="text-sm text-danger">{error}</div>}
    {material ? (edit ? <><Field label="SKU"><Input value={materialRow!.sku.name} readOnly /></Field><Field label="Supplier vendor"><Input value={materialRow!.supplier_vendor.name} readOnly /></Field><Field label="Unit"><Input value={`${materialRow!.unit.name} (${materialRow!.unit.code})`} readOnly /></Field></> : <><Field label="SKU" required><Select name="skuId" required><option value="">Select SKU</option>{refs.skus.map((sku) => <option key={sku.id} value={sku.id}>{sku.name}{sku.code ? ` (${sku.code})` : ""}</option>)}</Select></Field><Field label="Supplier vendor" required><Select name="vendorId" required><option value="">Select vendor</option>{refs.vendors.map((vendor) => <option key={vendor.id} value={vendor.id}>{vendor.name}</option>)}</Select></Field></>) : <><Field label="Name" required><Input name="name" defaultValue={workRow?.name} required /></Field><Field label="WORK category" required><Select name="categoryId" defaultValue={workRow?.category.id ?? ""} required><option value="">Select category</option>{refs.workCategories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</Select></Field><Field label="Vendor" required><Select name="vendorId" defaultValue={workRow?.vendor.id ?? ""} required><option value="">Select vendor</option>{refs.vendors.map((vendor) => <option key={vendor.id} value={vendor.id}>{vendor.name}</option>)}</Select></Field><Field label="Unit" required><Select name="unitId" defaultValue={workRow?.unit.id ?? ""} required><option value="">Select unit</option>{refs.units.map((unit) => <option key={unit.id} value={unit.id}>{unit.name} ({unit.code})</option>)}</Select></Field>{editor.kind === "material-labor" && <Field label="Scope note"><Input name="scopeNote" defaultValue={workRow?.scope_note ?? ""} /></Field>}</>}
    <Field label="Amount" required><Input name="amount" defaultValue={row?.amount ?? ""} inputMode="decimal" required /></Field><Field label="Currency" required><Input name="currency" defaultValue={row?.currency ?? "IDR"} maxLength={3} required onInput={(event) => { event.currentTarget.value = event.currentTarget.value.toUpperCase(); }} /></Field><Field label="Notes"><Input name="notes" defaultValue={row?.notes ?? ""} /></Field><FormActions><Button type="button" variant="ghost" onClick={onCancel}>Cancel</Button><Button type="submit" variant="primary">{edit ? "Save changes" : "Create price"}</Button></FormActions>
  </form></Dialog>;
}
