import { randomUUID } from "node:crypto";

import { type PrismaClient } from "@/generated/prisma/client";
import { type AuditActor } from "@platform/core/audit";
import { AppError } from "@platform/core/errors";
import { requirePermission, type PermissionGrants } from "@platform/core/rbac";
import { normalizeText } from "@platform/utilities/normalization";

import { MASTERDATA_PERMISSIONS, type MasterDataServicePorts, type TxClient, actorIsUsable, writeAudit } from "./shared";

const HELD = new Set(["BORROWED", "SENT_TO_CLIENT"]);
type Status = "AVAILABLE" | "BORROWED" | "SENT_TO_CLIENT" | "LOST" | "DISCARDED";

function place(value: string, field: string): string {
  const result = normalizeText(value).toUpperCase();
  if (result.length < 1 || result.length > 40) throw new AppError("VALIDATION", `SAMPLE_${field}_INVALID`, `${field} must be 1 to 40 characters.`);
  return result;
}
function optional(value: string | null | undefined, max: number, code: string): string | null {
  const result = normalizeText(value ?? "") || null;
  if (result && result.length > max) throw new AppError("VALIDATION", code, "Text is too long.");
  return result;
}
function qty(value: number | undefined): number { const n = value ?? 1; if (!Number.isInteger(n) || n < 1 || n > 999) throw new AppError("VALIDATION", "SAMPLE_QUANTITY_INVALID", "Quantity must be a whole number from 1 to 999."); return n; }
/** What a screen needs about one shelf sample; the SKU facts are flattened and an archived SKU is flagged, not hidden. */
export type SampleRead = {
  id: string; rack: string; box: string; quantity: number; locationNote: string | null; notes: string | null; status: Status;
  holderName: string | null; holderProjectId: string | null; holderProjectName: string | null; outSince: Date | null; sourceIntakeId: string | null;
  createdAt: Date; updatedAt: Date;
  skuId: string; skuCode: string | null; skuName: string | null; brandName: string | null; skuArchived: boolean;
};
function held(status: string): boolean { return HELD.has(status); }

async function movement(tx: TxClient, sample: { id: string; status: Status; holder_name: string | null; holder_project_name: string | null }, kind: "IN" | "OUT" | "RETURN" | "STATUS" | "MOVED" | "REMOVED", actor: AuditActor, extra: { fromRack?: string | null; fromBox?: string | null; toRack?: string | null; toBox?: string | null; note?: string | null } = {}) {
  await tx.sampleMovement.create({ data: { id: randomUUID(), sample_id: sample.id, kind, status_after: sample.status, holder_name: sample.holder_name, holder_project_name: sample.holder_project_name, from_rack: extra.fromRack ?? null, from_box: extra.fromBox ?? null, to_rack: extra.toRack ?? null, to_box: extra.toBox ?? null, note: extra.note ?? null, actor_user_id: actor.userId!, actor_label: actor.label } });
}

export function createSampleService(db: PrismaClient, ports: MasterDataServicePorts) {
  const write = ports.runTransaction;
  const read = (g: PermissionGrants) => requirePermission(g, MASTERDATA_PERMISSIONS.sampleRead);
  const manage = (g: PermissionGrants) => requirePermission(g, MASTERDATA_PERMISSIONS.sampleManage);
  async function sku(tx: TxClient, skuId: string) { const row = await tx.sku.findFirst({ where: { id: skuId, deleted_at: null } }); if (!row) throw new AppError("NOT_FOUND", "SAMPLE_SKU_NOT_FOUND", "SKU was not found."); }
  return {
    async listSamples(input: { grants: PermissionGrants; search?: string; status?: Status; rack?: string }): Promise<SampleRead[]> {
      read(input.grants); const search = normalizeText(input.search ?? "");
      const contains = (value: string) => ({ contains: value, mode: "insensitive" as const });
      const rows = await db.sample.findMany({ where: { deleted_at: null, ...(input.status ? { status: input.status } : {}), ...(input.rack ? { rack: place(input.rack, "RACK") } : {}), ...(search ? { OR: [{ rack: contains(search) }, { box: contains(search) }, { holder_name: contains(search) }, { holder_project_name: contains(search) }, { sku: { name: contains(search) } }, { sku: { code: contains(search) } }, { sku: { brand: { name: contains(search) } } }] } : {}) }, include: { sku: { include: { brand: { select: { name: true } } } } }, orderBy: [{ rack: "asc" }, { box: "asc" }, { sku: { name: "asc" } }] });
      return rows.map((row) => ({ id: row.id, rack: row.rack, box: row.box, quantity: row.quantity, locationNote: row.location_note, notes: row.notes, status: row.status, holderName: row.holder_name, holderProjectId: row.holder_project_id, holderProjectName: row.holder_project_name, outSince: row.out_since, sourceIntakeId: row.source_intake_id, createdAt: row.created_at, updatedAt: row.updated_at, skuId: row.sku_id, skuCode: row.sku.code, skuName: row.sku.name, brandName: row.sku.brand?.name ?? null, skuArchived: row.sku.deleted_at !== null }));
    },
    async getSampleSummary(input: { grants: PermissionGrants }) { read(input.grants); const grouped = await db.sample.groupBy({ by: ["status"], where: { deleted_at: null }, _count: true }); const counts = Object.fromEntries(grouped.map((r) => [r.status, r._count])); return { total: grouped.reduce((n, r) => n + r._count, 0), available: counts.AVAILABLE ?? 0, borrowed: counts.BORROWED ?? 0, sentToClient: counts.SENT_TO_CLIENT ?? 0, offShelf: (counts.LOST ?? 0) + (counts.DISCARDED ?? 0), racks: (await db.sample.findMany({ where: { deleted_at: null }, distinct: ["rack"], select: { rack: true } })).length }; },
    async listSampleRacks(input: { grants: PermissionGrants }) { read(input.grants); return (await db.sample.findMany({ where: { deleted_at: null }, distinct: ["rack"], orderBy: { rack: "asc" }, select: { rack: true } })).map((r) => r.rack); },
    /** SKUs a sample can be racked onto (live ones only), for the shelf's SKU picker; gated by the shelf permission, not the SKU one. */
    async listSampleSkuChoices(input: { grants: PermissionGrants }) {
      manage(input.grants);
      const rows = await db.sku.findMany({ where: { deleted_at: null }, orderBy: [{ name: "asc" }, { code: "asc" }], select: { id: true, name: true, code: true, brand: { select: { name: true } } } });
      return rows.map((sku) => ({ id: sku.id, name: sku.name, code: sku.code, brandName: sku.brand?.name ?? null }));
    },
    async getSampleHistory(input: { grants: PermissionGrants; sampleId: string }) { read(input.grants); return db.sampleMovement.findMany({ where: { sample_id: input.sampleId }, orderBy: [{ created_at: "desc" }, { id: "desc" }] }); },
    async createSample(input: { grants: PermissionGrants; actor: AuditActor; skuId: string; rack: string; box: string; quantity?: number; locationNote?: string | null; notes?: string | null }) { manage(input.grants); actorIsUsable(input.actor); return write(async (tx) => { await sku(tx, input.skuId); const row = await tx.sample.create({ data: { id: randomUUID(), sku_id: input.skuId, rack: place(input.rack, "RACK"), box: place(input.box, "BOX"), quantity: qty(input.quantity), location_note: optional(input.locationNote, 200, "SAMPLE_LOCATION_NOTE_INVALID"), notes: optional(input.notes, 1000, "SAMPLE_NOTES_INVALID") } }); await movement(tx, row, "IN", input.actor, { toRack: row.rack, toBox: row.box }); await writeAudit(ports, tx, { action: "masterdata.sample.created", entityType: "sample", entityId: row.id, actor: input.actor }); return row; }); },
    async updateSampleLocation(input: { grants: PermissionGrants; actor: AuditActor; sampleId: string; rack: string; box: string; quantity: number; locationNote?: string | null; notes?: string | null }) { manage(input.grants); actorIsUsable(input.actor); return write(async (tx) => { const before = await tx.sample.findFirst({ where: { id: input.sampleId, deleted_at: null } }); if (!before) throw new AppError("NOT_FOUND", "SAMPLE_NOT_FOUND", "Sample was not found."); const data = { rack: place(input.rack, "RACK"), box: place(input.box, "BOX"), quantity: qty(input.quantity), location_note: optional(input.locationNote, 200, "SAMPLE_LOCATION_NOTE_INVALID"), notes: optional(input.notes, 1000, "SAMPLE_NOTES_INVALID") }; if (before.rack === data.rack && before.box === data.box && before.quantity === data.quantity && before.location_note === data.location_note && before.notes === data.notes) return before; const row = await tx.sample.update({ where: { id: before.id }, data }); if (before.rack !== row.rack || before.box !== row.box) await movement(tx, row, "MOVED", input.actor, { fromRack: before.rack, fromBox: before.box, toRack: row.rack, toBox: row.box }); await writeAudit(ports, tx, { action: "masterdata.sample.location-updated", entityType: "sample", entityId: row.id, actor: input.actor }); return row; }); },
    async setSampleStatus(input: { grants: PermissionGrants; actor: AuditActor; sampleId: string; status: Status; holderName?: string | null; holderProjectId?: string | null; holderProjectName?: string | null; note?: string | null }) { manage(input.grants); actorIsUsable(input.actor); return write(async (tx) => { const before = await tx.sample.findFirst({ where: { id: input.sampleId, deleted_at: null } }); if (!before) throw new AppError("NOT_FOUND", "SAMPLE_NOT_FOUND", "Sample was not found."); const isHeld = held(input.status); const requestedName = optional(input.holderName, 120, "SAMPLE_HOLDER_INVALID"); const projectId = optional(input.holderProjectId, 120, "SAMPLE_PROJECT_INVALID"); const projectName = optional(input.holderProjectName, 200, "SAMPLE_PROJECT_INVALID"); const holderName = isHeld ? requestedName : null; if (isHeld && !holderName) throw new AppError("VALIDATION", "SAMPLE_HOLDER_REQUIRED", "A holder is required."); if (!isHeld && (projectId || projectName)) throw new AppError("VALIDATION", "SAMPLE_PROJECT_STATUS_INVALID", "A project is only allowed while a sample is out."); if ((projectId && !projectName) || (!projectId && projectName)) throw new AppError("VALIDATION", "SAMPLE_PROJECT_INVALID", "Project details must be complete."); if (before.status === input.status && before.holder_name === holderName && before.holder_project_id === projectId && before.holder_project_name === projectName) return before; const row = await tx.sample.update({ where: { id: before.id }, data: { status: input.status, holder_name: holderName, holder_project_id: projectId, holder_project_name: projectName, out_since: isHeld ? (held(before.status) ? before.out_since : new Date()) : null } }); const kind = isHeld ? "OUT" : before.status === "AVAILABLE" && (input.status === "LOST" || input.status === "DISCARDED") ? "STATUS" : held(before.status) && input.status === "AVAILABLE" ? "RETURN" : "STATUS"; await movement(tx, row, kind, input.actor, { note: optional(input.note, 1000, "SAMPLE_NOTE_INVALID") }); await writeAudit(ports, tx, { action: "masterdata.sample.status-updated", entityType: "sample", entityId: row.id, actor: input.actor }); return row; }); },
    async deleteSample(input: { grants: PermissionGrants; actor: AuditActor; sampleId: string }) { manage(input.grants); actorIsUsable(input.actor); return write(async (tx) => { const before = await tx.sample.findFirst({ where: { id: input.sampleId, deleted_at: null } }); if (!before) throw new AppError("NOT_FOUND", "SAMPLE_NOT_FOUND", "Sample was not found."); if (held(before.status)) throw new AppError("CONFLICT", "SAMPLE_OUT", "A sample that is out cannot be deleted."); const row = await tx.sample.update({ where: { id: before.id }, data: { deleted_at: new Date() } }); await movement(tx, row, "REMOVED", input.actor); await writeAudit(ports, tx, { action: "masterdata.sample.deleted", entityType: "sample", entityId: row.id, actor: input.actor }); return row; }); },
    async shelveSampleFromIntake(input: { grants: PermissionGrants; actor: AuditActor; intakeId: string; skuId: string; rack: string; box: string; quantity?: number; locationNote?: string | null }) { manage(input.grants); actorIsUsable(input.actor); return write(async (tx) => { const intake = await tx.sampleRequestIntake.findUnique({ where: { id: input.intakeId } }); if (!intake) throw new AppError("NOT_FOUND", "SAMPLE_INTAKE_NOT_FOUND", "Sample request was not found."); const existing = await tx.sample.findUnique({ where: { source_intake_id: intake.id } }); if (existing) throw new AppError("CONFLICT", "SAMPLE_ALREADY_SHELVED", "This request is already on the shelf."); await sku(tx, input.skuId); const row = await tx.sample.create({ data: { id: randomUUID(), source_intake_id: intake.id, sku_id: input.skuId, rack: place(input.rack, "RACK"), box: place(input.box, "BOX"), quantity: qty(input.quantity), location_note: optional(input.locationNote, 200, "SAMPLE_LOCATION_NOTE_INVALID") } }); if (!intake.sku_id) await tx.sampleRequestIntake.update({ where: { id: intake.id }, data: { sku_id: input.skuId } }); await movement(tx, row, "IN", input.actor, { toRack: row.rack, toBox: row.box }); await writeAudit(ports, tx, { action: "masterdata.sample.shelved", entityType: "sample", entityId: row.id, actor: input.actor, metadata: { intake_id: intake.id } }); await ports.sampleRequestNotifier?.shelved?.(tx, { intake: { id: intake.id, requesterUserId: intake.requester_user_id, sourceProjectId: intake.source_project_id, sourceProjectName: intake.source_project_name, productName: intake.product_name }, rack: row.rack, box: row.box }); return row; }); },
  };
}
