import assert from"node:assert/strict";import{describe,it}from"node:test";import type{TransactionClient}from"@platform/core/db";import{PricingService}from"./pricing-service";import type{PricingRepository,SkuPriceContext,SkuPriceRecord,SkuPriceWrite,WorkPriceContext,WorkPriceRecord,WorkPriceWrite}from"./pricing-repository";
const tx={}as TransactionClient,now=new Date("2026-08-26T06:00:00Z"),ctx={grants:["masterdata.price.read","masterdata.price.manage"],actor:{kind:"USER"as const,userId:"u",label:"Owner"}};
class Repo implements PricingRepository{sku:SkuPriceContext={sku:{id:"sku",status:"DRAFT",deletedAt:null,baseUnitId:"pcs",purchaseUnitId:null,brandId:null},unit:{id:"pcs",deletedAt:null},supplier:null,source:null,existing:null};workContext:WorkPriceContext={category:{kind:"WORK",deletedAt:null},unit:{deletedAt:null},vendor:null};works=new Map<string,WorkPriceRecord>();async loadSkuPriceContext(){return this.sku}async createSkuPrice(_t:TransactionClient,i:SkuPriceWrite){const x={...i,createdAt:now,updatedAt:now};this.sku.existing=x;return x}async updateSkuPrice(_t:TransactionClient,id:string,i:Omit<SkuPriceWrite,"id"|"skuId">){const x={...this.sku.existing!,...i,id,updatedAt:now};this.sku.existing=x;return x}async deleteSkuPrice(){this.sku.existing=null}async listWorkPrices(){return[...this.works.values()]}async findWorkPrice(_t:TransactionClient,id:string){return this.works.get(id)??null}async findLiveWorkCode(_t:TransactionClient,code:string,excludeId?:string){return[...this.works.values()].find(x=>!x.deletedAt&&x.id!==excludeId&&x.code.toLowerCase()===code.toLowerCase())??null}async loadWorkContext(){return this.workContext}async createWorkPrice(_t:TransactionClient,i:WorkPriceWrite){const x={...i,createdAt:now,updatedAt:now,deletedAt:null};this.works.set(x.id,x);return x}async updateWorkPrice(_t:TransactionClient,id:string,i:Omit<WorkPriceWrite,"id"|"code">){const x={...this.works.get(id)!,...i,id,updatedAt:now};this.works.set(id,x);return x}async setWorkDeletedAt(_t:TransactionClient,id:string,deletedAt:Date|null){const x={...this.works.get(id)!,deletedAt};this.works.set(id,x);return x}}
function h(){const repo=new Repo(),events:string[]=[];let n=0;const service=new PricingService({pricing:repo,generateId:()=>`id-${++n}`,now:()=>now,runTransaction:w=>w(tx),auditWriter:{write:async e=>{events.push(e.action)}}});return{repo,events,service}}
describe("PricingService",()=>{
 it("sets zero and updates the same canonical SkuPrice identity",async()=>{const x=h();const first=await x.service.setSkuPrice(ctx,{skuId:"sku",amount:"0",currency:"IDR",unitId:"pcs"});const second=await x.service.setSkuPrice(ctx,{skuId:"sku",amount:"100",currency:"IDR",unitId:"pcs"});assert.equal(second.id,first.id);assert.deepEqual(x.events,["sku-price.set","sku-price.updated"])});
 it("omits no-op and clears only Draft",async()=>{const x=h();await x.service.setSkuPrice(ctx,{skuId:"sku",amount:"10",currency:"IDR",unitId:"pcs"});const n=x.events.length;await x.service.setSkuPrice(ctx,{skuId:"sku",amount:"10",currency:"IDR",unitId:"pcs"});assert.equal(x.events.length,n);x.repo.sku.sku.status="ACTIVE";await assert.rejects(()=>x.service.clearSkuPrice(ctx,"sku"),{code:"SKU_PRICE_CLEAR_DRAFT_ONLY"});x.repo.sku.sku.status="DRAFT";await x.service.clearSkuPrice(ctx,"sku");assert.equal(x.events.at(-1),"sku-price.cleared")});
 it("rejects wrong price Unit and invalid supplier",async()=>{const x=h();x.repo.sku.unit={id:"box",deletedAt:null};await assert.rejects(()=>x.service.setSkuPrice(ctx,{skuId:"sku",amount:"1",currency:"IDR",unitId:"box"}),{code:"SKU_PRICE_UNIT_MISMATCH"})});
 it("creates bundled WorkPrice only with explicit scope and keeps code immutable",async()=>{const x=h();await assert.rejects(()=>x.service.createWorkPrice(ctx,{code:"WP-1",name:"Install",categoryId:"cat",unitId:"pcs",amount:"0",kind:"MATERIAL_LABOR",currency:"IDR"}),{code:"WORK_PRICE_SCOPE_REQUIRED"});const row=await x.service.createWorkPrice(ctx,{code:"WP-1",name:"Install",categoryId:"cat",unitId:"pcs",amount:"0",kind:"MATERIAL_LABOR",currency:"IDR",scopeNote:"Includes material and labor"});await assert.rejects(()=>x.service.updateWorkPrice(ctx,{id:row.id,code:"WP-2"}),{code:"WORK_PRICE_CODE_IMMUTABLE"});assert.equal(x.events.at(-1),"work-price.created")});
});
