import assert from "node:assert/strict";import{describe,it}from"node:test";import type{TransactionClient}from"@platform/core/db";import{SkuService}from"./sku-service";import type{SkuGraphInput,SkuRecord,SkuRepository}from"./sku-repository";import type{SkuRelationState}from"../domain/sku-rules";
const tx={}as TransactionClient,now=new Date("2026-08-26T05:00:00Z"),ctx={grants:["masterdata.sku.read","masterdata.sku.manage"],actor:{kind:"USER"as const,userId:"u",label:"Owner"}};const live=(id:string)=>({id,deletedAt:null});
class Repo implements SkuRepository{rows=new Map<string,SkuRecord>();relation:SkuRelationState={brand:null,category:null,baseUnit:live("unit"),purchaseUnit:null,dimensionUnit:null,skuPrices:[]};async list(){return[...this.rows.values()]}async findById(_t:TransactionClient,id:string){return this.rows.get(id)??null}async findLiveIdentityConflict(){return null}async loadRelationState(){return this.relation}async create(_t:TransactionClient,i:SkuGraphInput){const r={...i,createdAt:now,updatedAt:now,deletedAt:null};this.rows.set(r.id,r);return r}async update(_t:TransactionClient,id:string,i:SkuGraphInput){const r={...this.rows.get(id)!,...i,updatedAt:now};this.rows.set(id,r);return r}async setStatus(_t:TransactionClient,id:string,status:"DRAFT"|"ACTIVE"|"DISCONTINUED"){const r={...this.rows.get(id)!,status};this.rows.set(id,r);return r}async setDeletedAt(_t:TransactionClient,id:string,deletedAt:Date|null){const r={...this.rows.get(id)!,deletedAt};this.rows.set(id,r);return r}}
function h(){const repo=new Repo(),events:string[]=[];let n=0;const service=new SkuService({skus:repo,generateId:()=>`id-${++n}`,now:()=>now,runTransaction:w=>w(tx),auditWriter:{write:async e=>{events.push(e.action)}}});return{repo,events,service}}
describe("SkuService",()=>{
 it("creates truthful incomplete DRAFT without implicit defaults",async()=>{const x=h();const row=await x.service.create(ctx,{name:"Generic board",kind:"MATERIAL",baseUnitId:"unit"});assert.equal(row.status,"DRAFT");assert.equal(row.brandId,null);assert.equal(row.categoryId,null);assert.equal(row.purchaseUnitId,null);assert.deepEqual(x.events,["sku.created"])});
 it("requires explicit conversion when purchase Unit differs",async()=>{const x=h();x.repo.relation.purchaseUnit=live("box");await assert.rejects(()=>x.service.create(ctx,{name:"Board",kind:"MATERIAL",baseUnitId:"unit",purchaseUnitId:"box"}),{code:"SKU_CONVERSION_REQUIRED"})});
 it("activates only after category and supplier price readiness",async()=>{const x=h();const row=await x.service.create(ctx,{name:"Board",kind:"MATERIAL",baseUnitId:"unit"});await assert.rejects(()=>x.service.activate(ctx,row.id),{code:"SKU_ACTIVE_CATEGORY_REQUIRED"});x.repo.relation.category={id:"cat",kind:"PRODUCT",deletedAt:null};x.repo.relation.skuPrices=[{unitId:"unit"}];await x.service.update(ctx,{id:row.id,categoryId:"cat"});await x.service.activate(ctx,row.id);await x.service.discontinue(ctx,row.id);assert.deepEqual(x.events.slice(-2),["sku.activated","sku.discontinued"])});
 it("fails closed when a Unit edit would desynchronize a supplier price",async()=>{const x=h();const row=await x.service.create(ctx,{name:"Board",kind:"MATERIAL",baseUnitId:"unit"});x.repo.relation.purchaseUnit=live("box");x.repo.relation.skuPrices=[{unitId:"unit"}];await assert.rejects(()=>x.service.update(ctx,{id:row.id,purchaseUnitId:"box",conversion:"10"}),{code:"SKU_PRICE_UNIT_MISMATCH"})});
 it("aggregates media and omits a no-op update audit",async()=>{const x=h();const row=await x.service.create(ctx,{name:"Board",kind:"MATERIAL",baseUnitId:"unit",media:[{kind:"IMAGE",url:" https://example.com/a.jpg "}]});assert.equal(row.media[0]?.url,"https://example.com/a.jpg");const n=x.events.length;await x.service.update(ctx,{id:row.id});assert.equal(x.events.length,n)});
});
