import{Prisma}from"@/generated/prisma/client";import{toDecimalString,type DecimalString}from"@platform/utilities/decimal";import type{PricingRepository,SkuPriceRecord,WorkPriceRecord,WorkPriceWrite}from"../application/pricing-repository";
const d=(x:Prisma.Decimal):DecimalString=>toDecimalString(x.toFixed());const PRICE_SELECT={id:true,sku_id:true,supplier_party_id:true,amount:true,currency:true,unit_id:true,source_link_id:true,notes:true,created_at:true,updated_at:true,updated_by_user_id:true,updated_by_label:true}as const;type PriceRow=Prisma.SkuPriceGetPayload<{select:typeof PRICE_SELECT}>;function price(x:PriceRow):SkuPriceRecord{return{id:x.id,skuId:x.sku_id,supplierPartyId:x.supplier_party_id,amount:d(x.amount),currency:x.currency,unitId:x.unit_id,sourceLinkId:x.source_link_id,notes:x.notes,createdAt:x.created_at,updatedAt:x.updated_at,updatedByUserId:x.updated_by_user_id,updatedByLabel:x.updated_by_label};}
const WORK_SELECT={id:true,code:true,name:true,category_id:true,vendor_party_id:true,spec:true,dim_display:true,unit_id:true,amount:true,kind:true,currency:true,scope_note:true,notes:true,created_at:true,updated_at:true,deleted_at:true,updated_by_user_id:true,updated_by_label:true}as const;type WorkRow=Prisma.WorkPriceGetPayload<{select:typeof WORK_SELECT}>;function work(x:WorkRow):WorkPriceRecord{return{id:x.id,code:x.code,name:x.name,categoryId:x.category_id,vendorPartyId:x.vendor_party_id,spec:x.spec,dimensionDisplay:x.dim_display,unitId:x.unit_id,amount:d(x.amount),kind:x.kind,currency:x.currency,scopeNote:x.scope_note,notes:x.notes,createdAt:x.created_at,updatedAt:x.updated_at,deletedAt:x.deleted_at,updatedByUserId:x.updated_by_user_id,updatedByLabel:x.updated_by_label};}
const workData=(i:Omit<WorkPriceWrite,"id"|"code">)=>({name:i.name,category_id:i.categoryId,vendor_party_id:i.vendorPartyId,spec:i.spec===null?Prisma.DbNull:i.spec as Prisma.InputJsonValue,dim_display:i.dimensionDisplay,unit_id:i.unitId,amount:i.amount,kind:i.kind,currency:i.currency,scope_note:i.scopeNote,notes:i.notes,updated_by_user_id:i.updatedByUserId,updated_by_label:i.updatedByLabel});
export const prismaPricingRepository:PricingRepository={
 async loadSkuPriceContext(tx,i){const sku=await tx.sku.findFirst({where:{id:i.skuId},select:{id:true,status:true,deleted_at:true,base_unit_id:true,purchase_unit_id:true,brand_id:true,price:{select:PRICE_SELECT}}});if(!sku)return null;const unit=i.unitId?await tx.unit.findFirst({where:{id:i.unitId},select:{id:true,deleted_at:true}}):null;const supplier=i.supplierId?await tx.party.findFirst({where:{id:i.supplierId},select:{id:true,deleted_at:true,roles:{select:{role:true}}}}):null;const source=i.sourceId?await tx.brandLink.findFirst({where:{id:i.sourceId},select:{id:true,brand_id:true,brand:{select:{deleted_at:true}}}}):null;return{sku:{id:sku.id,status:sku.status,deletedAt:sku.deleted_at,baseUnitId:sku.base_unit_id,purchaseUnitId:sku.purchase_unit_id,brandId:sku.brand_id},unit:unit?{id:unit.id,deletedAt:unit.deleted_at}:null,supplier:supplier?{id:supplier.id,deletedAt:supplier.deleted_at,roles:supplier.roles.map(r=>r.role)}:null,source:source?{id:source.id,brandId:source.brand_id,brandDeletedAt:source.brand.deleted_at}:null,existing:sku.price?price(sku.price):null};},
 async createSkuPrice(tx,i){return price(await tx.skuPrice.create({data:{id:i.id,sku_id:i.skuId,supplier_party_id:i.supplierPartyId,amount:i.amount,currency:i.currency,unit_id:i.unitId,source_link_id:i.sourceLinkId,notes:i.notes,updated_by_user_id:i.updatedByUserId,updated_by_label:i.updatedByLabel},select:PRICE_SELECT}));},
 async updateSkuPrice(tx,id,i){return price(await tx.skuPrice.update({where:{id},data:{supplier_party_id:i.supplierPartyId,amount:i.amount,currency:i.currency,unit_id:i.unitId,source_link_id:i.sourceLinkId,notes:i.notes,updated_by_user_id:i.updatedByUserId,updated_by_label:i.updatedByLabel},select:PRICE_SELECT}));},async deleteSkuPrice(tx,id){await tx.skuPrice.delete({where:{id},select:{id:true}});},
 async listWorkPrices(tx,includeDeleted){return(await tx.workPrice.findMany({where:{deleted_at:includeDeleted?undefined:null},select:WORK_SELECT,orderBy:[{name:"asc"},{id:"asc"}]})).map(work);},async findWorkPrice(tx,id){const x=await tx.workPrice.findFirst({where:{id},select:WORK_SELECT});return x?work(x):null;},async findLiveWorkCode(tx,code,excludeId){const x=await tx.workPrice.findFirst({where:{deleted_at:null,id:excludeId?{not:excludeId}:undefined,code:{equals:code,mode:"insensitive"}},select:WORK_SELECT});return x?work(x):null;},
 async loadWorkContext(tx,i){const category=await tx.category.findFirst({where:{id:i.categoryId},select:{kind:true,deleted_at:true}});const unit=await tx.unit.findFirst({where:{id:i.unitId},select:{deleted_at:true}});const vendor=i.vendorId?await tx.party.findFirst({where:{id:i.vendorId},select:{id:true,deleted_at:true,roles:{select:{role:true}}}}):null;return{category:category?{kind:category.kind,deletedAt:category.deleted_at}:null,unit:unit?{deletedAt:unit.deleted_at}:null,vendor:vendor?{id:vendor.id,deletedAt:vendor.deleted_at,roles:vendor.roles.map(r=>r.role)}:null};},
 async createWorkPrice(tx,i){return work(await tx.workPrice.create({data:{id:i.id,code:i.code,...workData(i)},select:WORK_SELECT}));},async updateWorkPrice(tx,id,i){return work(await tx.workPrice.update({where:{id},data:workData(i),select:WORK_SELECT}));},async setWorkDeletedAt(tx,id,value){return work(await tx.workPrice.update({where:{id},data:{deleted_at:value},select:WORK_SELECT}));}
};
