import { Prisma } from "@/generated/prisma/client"; import type { DecimalString } from "@platform/utilities/decimal"; import { toDecimalString } from "@platform/utilities/decimal"; import type { SkuGraphInput, SkuRecord, SkuRepository } from "../application/sku-repository";
const INCLUDE={media:{select:{id:true,kind:true,url:true,label:true,sort_order:true},orderBy:[{sort_order:"asc" as const},{id:"asc" as const}]}} satisfies Prisma.SkuInclude; type Row=Prisma.SkuGetPayload<{include:typeof INCLUDE}>; const dec=(x:Prisma.Decimal|null):DecimalString|null=>x===null?null:toDecimalString(x.toFixed());
function map(x:Row):SkuRecord{return{id:x.id,code:x.code,name:x.name,slug:x.slug,brandId:x.brand_id,categoryId:x.category_id,kind:x.kind,status:x.status,spec:x.spec,dimensionLength:dec(x.dim_length),dimensionWidth:dec(x.dim_width),dimensionHeight:dec(x.dim_height),dimensionUnitId:x.dim_unit_id,dimensionDisplay:x.dim_display,baseUnitId:x.base_unit_id,purchaseUnitId:x.purchase_unit_id,conversion:dec(x.conversion),defaultWastePct:dec(x.default_waste_pct),minimumOrder:dec(x.minimum_order),roundingIncrement:dec(x.rounding_increment),notes:x.notes,media:x.media.map(m=>({id:m.id,kind:m.kind,url:m.url,label:m.label,sortOrder:m.sort_order})),createdAt:x.created_at,updatedAt:x.updated_at,deletedAt:x.deleted_at};}
const data=(i:SkuGraphInput)=>({code:i.code,name:i.name,slug:i.slug,brand_id:i.brandId,category_id:i.categoryId,kind:i.kind,status:i.status,spec:i.spec===null?Prisma.DbNull:i.spec as Prisma.InputJsonValue,dim_length:i.dimensionLength,dim_width:i.dimensionWidth,dim_height:i.dimensionHeight,dim_unit_id:i.dimensionUnitId,dim_display:i.dimensionDisplay,base_unit_id:i.baseUnitId,purchase_unit_id:i.purchaseUnitId,conversion:i.conversion,default_waste_pct:i.defaultWastePct,minimum_order:i.minimumOrder,rounding_increment:i.roundingIncrement,notes:i.notes});
async function read(tx:Parameters<SkuRepository["findById"]>[0],id:string){return map(await tx.sku.findUniqueOrThrow({where:{id},include:INCLUDE}));}
async function syncMedia(tx:Parameters<SkuRepository["update"]>[0],i:SkuGraphInput){await tx.skuMedia.deleteMany({where:{sku_id:i.id,id:{notIn:i.media.map(m=>m.id)}}});for(const m of i.media){const r=await tx.skuMedia.updateMany({where:{id:m.id,sku_id:i.id},data:{kind:m.kind,url:m.url,label:m.label,sort_order:m.sortOrder}});if(!r.count)await tx.skuMedia.create({data:{id:m.id,sku_id:i.id,kind:m.kind,url:m.url,label:m.label,sort_order:m.sortOrder},select:{id:true}});}}
export const prismaSkuRepository:SkuRepository={
 async list(tx,f){return(await tx.sku.findMany({where:{deleted_at:f.includeDeleted?undefined:null,brand_id:f.brandId,category_id:f.categoryId,status:f.status,OR:f.query?[{name:{contains:f.query,mode:"insensitive"}},{code:{contains:f.query,mode:"insensitive"}},{slug:{contains:f.query,mode:"insensitive"}}]:undefined},include:INCLUDE,orderBy:[{name:"asc"},{id:"asc"}]})).map(map);},
 async findById(tx,id){const x=await tx.sku.findFirst({where:{id},include:INCLUDE});return x?map(x):null;},
 async findLiveIdentityConflict(tx,i){const scope=i.brandId===null?{brand_id:null}:{brand_id:i.brandId};const x=await tx.sku.findFirst({where:{...scope,deleted_at:null,id:i.id?{not:i.id}:undefined,OR:[{slug:{equals:i.slug,mode:"insensitive"}},...(i.code?[{code:{equals:i.code,mode:"insensitive" as const}}]:[])]},include:INCLUDE});return x?map(x):null;},
 async loadRelationState(tx,i){const brand=i.brandId?await tx.brand.findFirst({where:{id:i.brandId},select:{id:true,deleted_at:true}}):null;const category=i.categoryId?await tx.category.findFirst({where:{id:i.categoryId},select:{id:true,kind:true,deleted_at:true}}):null;const baseUnit=await tx.unit.findFirst({where:{id:i.baseUnitId},select:{id:true,deleted_at:true}});const purchaseUnit=i.purchaseUnitId?await tx.unit.findFirst({where:{id:i.purchaseUnitId},select:{id:true,deleted_at:true}}):null;const dimensionUnit=i.dimensionUnitId?await tx.unit.findFirst({where:{id:i.dimensionUnitId},select:{id:true,deleted_at:true}}):null;const price=i.skuId?await tx.skuPrice.findFirst({where:{sku_id:i.skuId},select:{unit_id:true}}):null;return{brand:brand?{id:brand.id,deletedAt:brand.deleted_at}:null,category:category?{id:category.id,kind:category.kind,deletedAt:category.deleted_at}:null,baseUnit:baseUnit?{id:baseUnit.id,deletedAt:baseUnit.deleted_at}:null,purchaseUnit:purchaseUnit?{id:purchaseUnit.id,deletedAt:purchaseUnit.deleted_at}:null,dimensionUnit:dimensionUnit?{id:dimensionUnit.id,deletedAt:dimensionUnit.deleted_at}:null,hasCanonicalPrice:price!==null,canonicalPriceUnitId:price?.unit_id??null};},
 async create(tx,i){await tx.sku.create({data:{id:i.id,...data(i)},select:{id:true}});if(i.media.length)await tx.skuMedia.createMany({data:i.media.map(m=>({id:m.id,sku_id:i.id,kind:m.kind,url:m.url,label:m.label,sort_order:m.sortOrder}))});return read(tx,i.id);},
 async update(tx,id,i){await tx.sku.update({where:{id},data:data(i),select:{id:true}});await syncMedia(tx,i);return read(tx,id);},
 async setStatus(tx,id,status){await tx.sku.update({where:{id},data:{status},select:{id:true}});return read(tx,id);},async setDeletedAt(tx,id,value){await tx.sku.update({where:{id},data:{deleted_at:value},select:{id:true}});return read(tx,id);}
};
