import assert from "node:assert/strict";
import { after, before, beforeEach, describe, it } from "node:test";
import { createAuditEventWriter } from "@platform/core/audit/persistence";
import { ImportExportService, type WorkbookData } from "../application/import-export";
import { BrandService } from "../application/brand-service"; import { BusinessTypeService } from "../application/business-type-service"; import { CategoryService } from "../application/category-service"; import { PartyService } from "../application/party-service"; import { PricingService } from "../application/pricing-service"; import { SkuService } from "../application/sku-service"; import { UnitService } from "../application/unit-service";
import { prismaBrandRepository } from "./brand-repository-prisma"; import { prismaCategoryRepository } from "./category-repository-prisma"; import { prismaPartyRepository, prismaBusinessTypeRepository } from "./party-repository-prisma"; import { prismaPricingRepository } from "./pricing-repository-prisma"; import { prismaSkuRepository } from "./sku-repository-prisma"; import { prismaUnitRepository } from "./unit-repository-prisma";
import { closeTestDb, createTestDb, requireDisposableTestDatabaseUrl, truncateAllTables, type TestDb } from "./test-db"; import { createTransactionRunner } from "./transaction"; import { createWorkbookApplier } from "./workbook-applier"; import { prismaWorkbookStore } from "./workbook-store-prisma"; import { xlsxWorkbookCodec } from "./xlsx-workbook";

const context={grants:["masterdata.import.execute","masterdata.export.read","masterdata.dictionary.read","masterdata.dictionary.manage","masterdata.party.read","masterdata.party.manage","masterdata.brand.read","masterdata.brand.manage","masterdata.category.read","masterdata.category.manage","masterdata.sku.read","masterdata.sku.manage","masterdata.price.read","masterdata.price.manage"],actor:{kind:"USER" as const,userId:"import-user",label:"Import user"}};
type MutableWorkbook={manifest:WorkbookData["manifest"];sheets:Record<keyof WorkbookData["sheets"],Record<string,unknown>[]>};
describe("whole-schema workbook applier",()=>{let db:TestDb;let seq=0;before(async()=>{db=await createTestDb(requireDisposableTestDatabaseUrl())});beforeEach(async()=>{await truncateAllTables(db);seq=0});after(async()=>closeTestDb(db));
function harness(){const common={runTransaction:createTransactionRunner(db.prisma),auditWriter:createAuditEventWriter(),generateId:()=>`00000000-0000-4000-8000-${String(++seq).padStart(12,"0")}`,now:()=>new Date("2026-08-27T04:00:00.000Z")};const units=new UnitService({...common,units:prismaUnitRepository}),businessTypes=new BusinessTypeService({...common,businessTypes:prismaBusinessTypeRepository}),categories=new CategoryService({...common,categories:prismaCategoryRepository}),parties=new PartyService({...common,parties:prismaPartyRepository}),brands=new BrandService({...common,brands:prismaBrandRepository}),skus=new SkuService({...common,skus:prismaSkuRepository}),pricing=new PricingService({...common,pricing:prismaPricingRepository});const service=new ImportExportService({runTransaction:common.runTransaction,codec:xlsxWorkbookCodec,store:prismaWorkbookStore,applier:createWorkbookApplier({units,businessTypes,categories,parties,brands,skus,pricing}),auditWriter:common.auditWriter,now:common.now,generateId:common.generateId});return{service,units,categories,parties,brands};}
it("preserves omitted relationships and rolls the whole workbook back on a late invalid row",async()=>{const h=harness();const unit=await h.units.create(context,{code:"pcs",label:"Pieces",usages:["QUANTITY"]});const category=await h.categories.create(context,{kind:"PRODUCT",name:"Lighting"});const party=await h.parties.create(context,{name:"Acme",type:"ORGANIZATION",roles:["MATERIAL_SUPPLIER"],businessTypeIds:[]});const brand=await h.brands.create(context,{name:"Original",ownerPartyId:party.id,categories:[{categoryId:category.id}]});
const exported=await h.service.export(context);const data=structuredClone(await xlsxWorkbookCodec.decode(exported)) as unknown as MutableWorkbook;data.sheets.Brand[0]!.name="Updated";data.sheets.BrandCategory=[];const edited=await xlsxWorkbookCodec.encode(data as unknown as WorkbookData);const preview=await h.service.preview(context,edited);assert.equal(preview.issues.length,0);await h.service.apply(context,preview);assert.equal((await db.prisma.brand.findUniqueOrThrow({where:{id:brand.id},include:{categories:true}})).categories.length,1);
const fresh=structuredClone(await xlsxWorkbookCodec.decode(await h.service.export(context))) as typeof data;fresh.sheets.Unit[0]!.label="Must roll back";fresh.sheets.Category.push({id:"00000000-0000-4000-8000-999999999999",kind:"WORK",name:"Invalid child",parent_id:"00000000-0000-4000-8000-888888888888",updated_at:null});const badBytes=await xlsxWorkbookCodec.encode(fresh as unknown as WorkbookData);const badPreview=await h.service.preview(context,badBytes);assert.equal(badPreview.issues.length,0);await assert.rejects(()=>h.service.apply(context,badPreview));assert.equal((await db.prisma.unit.findUniqueOrThrow({where:{id:unit.id}})).label,"Pieces");});
});
