"use client";

import { useActionState, useState, useEffect } from "react";
import { ChevronDown, ChevronRight, X } from "lucide-react";
import type { ActionResult } from "@platform/core/actions";
import {
  Button,
  Checkbox,
  CopyButton,
  DraftDialog,
  Field,
  FilterChip,
  FormActions,
  IconButton,
  InlineError,
  Input,
  RadioGroup,
  RowActionMenu,
  Surface,
  Textarea,
} from "@/platform/ui_engine";
import { DeliverableForm } from "./files/file-controls";
import { GeneralTaskBlock } from "./general-task-block";

import {
  openIterationAction,
  sendIterationAction,
  finishPhaseAction,
  startSupervisionAction,
  finishSupervisionAction,
  reopenSupervisionAction,
  voidIterationAction,
  reopenPhaseAction,
  closePhaseByExceptionAction,
  recordInternalApprovalAction,
  recordResponseAndFinishAction,
} from "./phase-actions";

// ── Types ─────────────────────────────────────────────────────────────────────

export type IterationPoint = {
  id: string;
  text: string;
  done: boolean;
  source: "INTERNAL" | "CLIENT_REVISION";
  withdrawn_at: string | null;
};

export type IterationItem = {
  id: string;
  number: number;
  state: "DRAFT" | "SENT" | "APPROVED" | "SUPERSEDED" | "VOIDED";
  sent_at: string | null;
  created_at: string;
  void_reason: string | null;
  internal_approval: { approver: string; at: string } | null;
  points: IterationPoint[];
};

export type PhaseDeliverable = {
  /** Standard filename generated by the naming template (SfFile.filename). */
  filename: string;
  original_filename: string;
  treatment: "RECORDED" | "STORED" | "LINKED";
  /** File size as a decimal string (BigInt serialized across the server/client boundary). */
  bytes: string;
  bytes_label: string;
  dropped_at: string;
  dropped_at_label: string;
  external_url: string | null;
  /** Round label of the iteration this file was sent in, or null if still draft. */
  sent_round_label: string | null;
};

export type PhaseItem = {
  id: string;
  name: string;
  key: string;
  /** Folder key linking this phase to its deliverable files. null for phases with no output folder. */
  folder_key: string | null;
  state: "NOT_STARTED" | "IN_PROGRESS" | "WAITING_CLIENT" | "DONE";
  has_rounds: boolean;
  round_prefix: string | null;
  requires_internal_approval: boolean;
  /** Current (non-superseded) deliverable for this phase, or null if none recorded yet. */
  currentFile: PhaseDeliverable | null;
  /** Preview of the next standard filename for this phase. null when phase is DONE or has no folder. */
  nextFilename: string | null;
  tasks: import("./general-task-block").TaskItem[];
  iterations: IterationItem[];
};

// ── Helpers ───────────────────────────────────────────────────────────────────

function ageLabel(since: string): string {
  const ms = Date.now() - new Date(since).getTime();
  const days = Math.floor(ms / 86_400_000);
  if (days === 0) return "today";
  if (days === 1) return "1 day";
  return `${days} days`;
}

function iterLabel(phase: PhaseItem, number: number): string {
  const prefix = phase.round_prefix ?? phase.key;
  return `${prefix}${number}`;
}

const PHASE_STATE_LABELS: Record<string, string> = {
  NOT_STARTED: "Not started",
  IN_PROGRESS: "In progress",
  WAITING_CLIENT: "Waiting for client",
  DONE: "Complete",
};

const ITER_STATE_LABELS: Record<string, string> = {
  DRAFT: "not started",
  SENT: "sent",
  APPROVED: "approved",
  SUPERSEDED: "revised",
  VOIDED: "voided",
};

// ── Send Dialog ───────────────────────────────────────────────────────────────

function SendDialog({
  iterationId,
  label,
  projectId,
  openPoints,
  missingApproval,
  onClose,
}: {
  iterationId: string;
  label: string;
  projectId: string;
  openPoints: number;
  missingApproval: boolean;
  onClose: () => void;
}) {
  const [state, action, pending] = useActionState(
    sendIterationAction.bind(null, projectId, iterationId),
    null as ActionResult<void> | null,
  );

  useEffect(() => {
    if (state?.ok) onClose();
  }, [state, onClose]);

  const error = state?.ok === false ? state.error.safeMessage : null;

  return (
    <DraftDialog
      open
      pending={pending}
      onOpenChange={(open) => { if (!open) onClose(); }}
      title={`Send ${label} to client`}
      description="This only records the send; the material still goes out through the studio's usual channel."
      size="sm"
    >
      {openPoints > 0 && (
        <div className="mb-4 text-sm text-ink-secondary bg-surface-muted rounded-action px-3 py-2 border border-line">
          <strong>{openPoints} points</strong> in {label} are still open.
        </div>
      )}
      {missingApproval && (
        <div className="mb-4 text-sm text-ink-secondary bg-surface-muted rounded-action px-3 py-2 border border-line">
          This round has no internal approval yet. The send can still be recorded.
        </div>
      )}

      {error && <InlineError className="mb-3">{error}</InlineError>}

      <form action={action}>
        <FormActions>
        <Button variant="ghost" size="sm" data-dialog-cancel disabled={pending}>
          Cancel
        </Button>
        <Button variant="primary" size="sm" type="submit" disabled={pending}>
          {pending ? "Saving…" : openPoints > 0 ? "Send anyway" : "Send"}
          </Button>
        </FormActions>
      </form>
    </DraftDialog>
  );
}

// ── Response Dialog ───────────────────────────────────────────────────────────

function ResponseDialog({
  iterationId,
  label,
  projectId,
  canFinishPhase,
  onClose,
}: {
  iterationId: string;
  label: string;
  projectId: string;
  canFinishPhase: boolean;
  onClose: () => void;
}) {
  const [kind, setKind] = useState<"APPROVAL" | "REVISION">("APPROVAL");
  const [points, setPoints] = useState<string[]>([""]);
  const [alsoFinish, setAlsoFinish] = useState(false);
  const [state, action, pending] = useActionState(
    recordResponseAndFinishAction.bind(null, projectId, iterationId),
    null as ActionResult<void> | null,
  );

  useEffect(() => {
    if (state?.ok) onClose();
  }, [state, onClose]);

  const error = state?.ok === false ? state.error.safeMessage : null;

  function addPoint() {
    setPoints((p) => [...p, ""]);
  }
  function updatePoint(i: number, val: string) {
    setPoints((p) => p.map((v, idx) => (idx === i ? val : v)));
  }
  function removePoint(i: number) {
    setPoints((p) => p.filter((_, idx) => idx !== i));
  }

  return (
    <DraftDialog
      open
      pending={pending}
      watchedValue={JSON.stringify([kind, points, alsoFinish])}
      onOpenChange={(open) => { if (!open) onClose(); }}
      title={`Client response for ${label}`}
      size="sm"
    >
      <form action={action} className="flex flex-col gap-4">
        {/* Kind picker */}
        <RadioGroup
          label="Client response"
          name="kind"
          value={kind}
          onValueChange={(value) => setKind(value as typeof kind)}
          options={[
            { value: "APPROVAL", label: "Approved" },
            { value: "REVISION", label: "Revision requested" },
          ]}
        />

        {/* Revision points */}
        {kind === "REVISION" && (
          <div className="flex flex-col gap-2 pl-4 border-l-2 border-line">
            <p className="text-xs font-medium text-ink-secondary uppercase tracking-wide">
              Revision points
            </p>
            {points.map((pt, i) => (
              <div key={i} className="flex items-center gap-1.5">
                <Input
                  type="text"
                  name="point"
                  density="compact"
                  value={pt}
                  onChange={(e) => updatePoint(i, e.target.value)}
                  placeholder={`Point ${i + 1}`}
                  className="min-w-0 flex-1"
                />
                {points.length > 1 && (
                  <IconButton
                    size="sm"
                    variant="ghost"
                    label="Remove point"
                    icon={<X aria-hidden="true" />}
                    onClick={() => removePoint(i)}
                    className="shrink-0"
                  />
                )}
              </div>
            ))}
            <Button variant="ghost" size="sm" onClick={addPoint} className="self-start">
              + Add point
            </Button>
            <p className="text-xs text-ink-tertiary">
              Points are added to the next round. A new round is created
              automatically if none exists.
            </p>
          </div>
        )}

        {/* Optional note */}
        <Field label="Notes (optional)">
          <Textarea name="note" rows={2} density="compact" placeholder="Notes from the client…" className="min-h-16 resize-none" />
        </Field>

        {/* Sekalian selesaikan — APPROVAL only, when no other open iterations */}
        {kind === "APPROVAL" && canFinishPhase && (
          <Checkbox
            checked={alsoFinish}
            onCheckedChange={(checked) => setAlsoFinish(checked === true)}
            label="Finish this phase too"
            className="text-sm text-ink-secondary"
          />
        )}
        {alsoFinish && <input type="hidden" name="also_finish" value="1" />}

        {error && <InlineError>{error}</InlineError>}

        <FormActions>
          <Button variant="ghost" size="sm" data-dialog-cancel disabled={pending}>
            Cancel
          </Button>
          <Button variant="primary" size="sm" type="submit" disabled={pending}>
            {pending ? "Saving…" : "Save response"}
          </Button>
        </FormActions>
      </form>
    </DraftDialog>
  );
}


// ── Void Dialog ───────────────────────────────────────────────────────────────

function VoidDialog({
  iterationId,
  label,
  projectId,
  onClose,
}: {
  iterationId: string;
  label: string;
  projectId: string;
  onClose: () => void;
}) {
  const [state, action, pending] = useActionState(
    voidIterationAction.bind(null, projectId, iterationId),
    null as ActionResult<void> | null,
  );

  useEffect(() => {
    if (state?.ok) onClose();
  }, [state, onClose]);

  const error = state?.ok === false ? state.error.safeMessage : null;

  return (
    <DraftDialog
      open
      pending={pending}
      onOpenChange={(open) => { if (!open) onClose(); }}
      title={`Stop round ${label}?`}
      description="The round is stopped and cannot continue. Its number and contents stay in the history."
      size="sm"
    >
      <form action={action} className="flex flex-col gap-3">
        <div>
          <label className="block text-xs font-medium text-ink-secondary mb-1">
            Reason <span className="text-danger">*</span>
          </label>
          <Textarea
            name="reason"
            rows={2}
            required
            placeholder="Why is this round being stopped?…"
            className="w-full text-sm border border-line rounded-action px-2 py-1.5 bg-transparent text-ink placeholder:text-ink-tertiary focus:outline-none focus:border-line-focus resize-none"
          />
        </div>
        {error && <InlineError>{error}</InlineError>}
        <FormActions>
          <Button variant="ghost" size="sm" data-dialog-cancel disabled={pending}>
            Cancel
          </Button>
          <Button variant="danger-primary" size="sm" type="submit" disabled={pending}>
            {pending ? "Stopping…" : "Stop round"}
          </Button>
        </FormActions>
      </form>
    </DraftDialog>
  );
}

// ── Reopen Phase Dialog ──────────────────────────────────────────────────────

function ReopenPhaseDialog({
  phaseId,
  phaseName,
  hasRounds,
  projectId,
  onClose,
}: {
  phaseId: string;
  phaseName: string;
  hasRounds: boolean;
  projectId: string;
  onClose: () => void;
}) {
  const [state, action, pending] = useActionState(
    (hasRounds ? reopenPhaseAction : reopenSupervisionAction).bind(null, projectId, phaseId),
    null as ActionResult<void> | null,
  );
  useEffect(() => { if (state?.ok) onClose(); }, [state, onClose]);
  const error = state?.ok === false ? state.error.safeMessage : null;
  return (
    <DraftDialog
      open
      pending={pending}
      onOpenChange={(open) => { if (!open) onClose(); }}
      title={`Reopen phase ${phaseName}?`}
      description={hasRounds ? "The phase reopens; a new round can be started after this." : "Supervision returns to in progress."}
      size="sm"
    >
      <form action={action} className="flex flex-col gap-3">
        <div className="flex flex-col gap-1">
          <label className="text-xs font-medium text-ink-secondary">Reason *</label>
          <Textarea
            name="reason"
            required
            rows={2}
            placeholder="Why is this phase being reopened?"
            className="resize-none"
          />
        </div>
        {error && <InlineError>{error}</InlineError>}
        <FormActions>
          <Button variant="secondary" size="sm" data-dialog-cancel>
          Cancel
          </Button>
          <Button variant="primary" size="sm" type="submit" disabled={pending}>
          {pending ? "Reopening…" : "Reopen"}
          </Button>
        </FormActions>
      </form>
    </DraftDialog>
  );
}

// ── Close By Exception Dialog ─────────────────────────────────────────────────

function CloseByExceptionDialog({
  phaseId,
  phaseName,
  projectId,
  onClose,
}: {
  phaseId: string;
  phaseName: string;
  projectId: string;
  onClose: () => void;
}) {
  const [state, action, pending] = useActionState(
    closePhaseByExceptionAction.bind(null, projectId, phaseId),
    null as ActionResult<void> | null,
  );
  useEffect(() => { if (state?.ok) onClose(); }, [state, onClose]);
  const error = state?.ok === false ? state.error.safeMessage : null;
  return (
    <DraftDialog
      open
      pending={pending}
      onOpenChange={(open) => { if (!open) onClose(); }}
      title={`Close phase ${phaseName} as an exception?`}
      description="The phase closes without approving its last round. No round may still be a draft or sent."
      size="sm"
    >
      <form action={action} className="flex flex-col gap-3">
        <div className="flex flex-col gap-1">
          <label className="text-xs font-medium text-ink-secondary">Exception reason *</label>
          <Textarea
            name="reason"
            required
            rows={2}
            placeholder="Why is this phase closing early?"
            className="resize-none"
          />
        </div>
        {error && <InlineError>{error}</InlineError>}
        <FormActions>
          <Button variant="secondary" size="sm" data-dialog-cancel>
            Cancel
          </Button>
          <Button variant="danger-primary" size="sm" type="submit" disabled={pending}>
            {pending ? "Closing…" : "Close as exception"}
          </Button>
        </FormActions>
      </form>
    </DraftDialog>
  );
}

// ── Iteration Block ───────────────────────────────────────────────────────────

function IterationBlock({
  iteration,
  phase,
  projectId,
  canReview,
  onSend,
  onRespond,
  onVoid,
}: {
  iteration: IterationItem;
  phase: PhaseItem;
  projectId: string;
  canReview: boolean;
  onSend: (id: string, label: string, openPoints: number, missingApproval: boolean) => void;
  onRespond: (id: string, label: string, canFinishPhase: boolean) => void;
  onVoid: (id: string, label: string) => void;
}) {
  const label = iterLabel(phase, iteration.number);
  const isDraft = iteration.state === "DRAFT";
  const isSent = iteration.state === "SENT";
  const isVoided = iteration.state === "VOIDED";
  const isSuperseded = iteration.state === "SUPERSEDED";
  const isActive = isDraft || isSent;

  const activePoints = iteration.points.filter((p) => !p.withdrawn_at);
  const openPoints = activePoints.filter((p) => !p.done).length;

  const sentAgeText =
    isSent && iteration.sent_at
      ? `sent ${ageLabel(iteration.sent_at)} ago`
      : ITER_STATE_LABELS[iteration.state] ?? iteration.state;

  const [approvalState, approvalAction, approvalPending] = useActionState(
    recordInternalApprovalAction.bind(null, projectId, iteration.id),
    null as ActionResult<void> | null,
  );
  const approvalError = approvalState?.ok === false ? approvalState.error.safeMessage : null;

  return (
    <div
      className={[
        "flex flex-col gap-1.5 rounded-action px-3 py-2.5",
        isActive
          ? "border border-line bg-surface"
          : "border border-transparent",
        isVoided || isSuperseded ? "opacity-60" : "",
      ]
        .filter(Boolean)
        .join(" ")}
    >
      {/* Label + state + action */}
      <div className="flex items-center gap-2 min-w-0">
        <span
          className={`text-sm font-medium shrink-0 ${
            isDraft
              ? "text-ink"
              : isVoided || isSuperseded
              ? "text-ink-tertiary"
              : "text-ink-secondary"
          }`}
        >
          {label}
        </span>
        <span className="flex-1 min-w-0 text-sm text-ink-tertiary truncate">
          {isSent ? sentAgeText : ITER_STATE_LABELS[iteration.state] ?? iteration.state}
        </span>

        {/* ACC indicator — when internal_approval exists */}
        {iteration.internal_approval && (
          <span className="shrink-0 text-xs text-ink-tertiary">
            ACC {iteration.internal_approval.approver}
          </span>
        )}

        {isDraft && phase.requires_internal_approval && !iteration.internal_approval && canReview && (
          <form action={approvalAction}>
            <Button variant="secondary" size="sm" type="submit" disabled={approvalPending}>
              {approvalPending ? "Recording…" : "ACC"}
            </Button>
          </form>
        )}

        {/* Primary action — never two at once */}
        {isDraft && canReview && (
          <Button

 onClick={() =>
 onSend(
 iteration.id,
 label,
 openPoints,
 phase.requires_internal_approval && !iteration.internal_approval,
 )
 }
 variant="secondary" size="sm" className="shrink-0"
 >
            Send to client
          </Button>
        )}
        {isSent && canReview && (
          <Button

 onClick={() => {
 const otherOpen = phase.iterations.some(
 (i) => i.id !== iteration.id && (i.state === "DRAFT" || i.state === "SENT"),
 );
 onRespond(iteration.id, label, !otherOpen);
 }}
 variant="secondary" size="sm" className="shrink-0"
 >
            Record client response
          </Button>
        )}
        {/* ⋯ menu — void, withdraw send (disabled until service supports it) */}
        {(isDraft || isSent) && canReview && (
          <RowActionMenu
            label={`Actions for ${label}`}
            items={[
              ...(isSent
                ? [
                    {
                      label: "Withdraw send",
                      disabled: true,
                      onSelect: () => {},
                    } as const,
                  ]
                : []),
              {
              label: "Stop round",
                danger: true,
                separatorBefore: isSent,
                onSelect: () => onVoid(iteration.id, label),
              },
            ]}
          />
        )}
      </div>

      {approvalError && <InlineError>{approvalError}</InlineError>}

      {/* Revision points checklist (DRAFT only, when points exist) */}
      {isDraft && activePoints.length > 0 && (
        <div className="flex flex-col gap-1 ml-10 mt-0.5">
          {activePoints.map((point) => (
            <div key={point.id} className="flex items-start gap-1.5">
              <span
                className={`shrink-0 text-xs mt-0.5 ${
                  point.done
                    ? "text-success"
                    : "text-ink-tertiary"
                }`}
              >
                {point.done ? "✓" : "○"}
              </span>
              <span
                className={`text-xs leading-relaxed ${
                  point.done
                    ? "line-through text-ink-tertiary"
                    : "text-ink-secondary"
                } ${point.source === "CLIENT_REVISION" && !point.done ? "italic" : ""}`}
              >
                {point.text}
              </span>
            </div>
          ))}
        </div>
      )}

      {/* Void reason (VOIDED only) */}
      {isVoided && iteration.void_reason && (
        <p className="text-xs text-ink-tertiary mt-0.5 ml-1 italic">
          Reason: {iteration.void_reason}
        </p>
      )}
    </div>
  );
}

// ── Phase Deliverable Block ────────────────────────────────────────────────────

function PhaseDeliverableBlock({
  phase,
  projectId,
  canManage,
}: {
  phase: PhaseItem;
  projectId: string;
  canManage: boolean;
}) {
  const { currentFile, nextFilename, folder_key } = phase;
  const isDone = phase.state === "DONE";

  // Nothing to show if there's no folder assignment for this phase.
  if (!folder_key) return null;

  return (
    <div className="border border-line rounded-md bg-surface-muted px-3 py-2.5 flex flex-col gap-2">
      {/* Current deliverable summary */}
      <div className="flex flex-col gap-0.5">
        <p className="text-xs font-medium text-ink">Current deliverable</p>
        {currentFile ? (
          <>
          <div className="flex items-center gap-1.5">
            <span className="text-xs font-medium text-ink truncate" title={currentFile.filename}>
              {currentFile.filename}
            </span>
            <span className="text-xs text-ink-secondary shrink-0">
              · {currentFile.sent_round_label ? `Sent in ${currentFile.sent_round_label}` : "Not sent"}
            </span>
          </div>
          <div className="flex items-center gap-2 text-xs text-ink-tertiary">
            <span>{currentFile.treatment}</span>
            <span>·</span>
            <span>{currentFile.bytes_label}</span>
            <span>·</span>
            <span>{currentFile.dropped_at_label}</span>
          </div>
          <p className="text-xs text-ink-tertiary truncate" title={currentFile.original_filename}>
            Original: {currentFile.original_filename}
          </p>
          {currentFile.external_url ? (
            <a
              href={currentFile.external_url}
              target="_blank"
              rel="noreferrer"
              className="text-xs text-action hover:underline"
            >
              Open external link
            </a>
          ) : null}
          </>
        ) : (
          <p className="text-xs text-ink-tertiary">No deliverable recorded yet.</p>
        )}
      </div>

      {/* Next filename preview with copy button (projectRead — always visible) */}
      {!isDone && nextFilename && (
        <div className="flex items-center gap-1">
          <span className="text-xs font-ui-mono text-ink-secondary truncate" title={nextFilename}>
            {nextFilename}
          </span>
          <CopyButton value={nextFilename} label="Copy filename" />
        </div>
      )}

      {/* Intake form — only for managers on non-DONE phases */}
      {canManage && !isDone && (
        <div className="pt-1 border-t border-line">
          <DeliverableForm projectId={projectId} fixedFolderKey={folder_key} />
        </div>
      )}
    </div>
  );
}

// ── Phase Block ───────────────────────────────────────────────────────────────

function PhaseBlock({
  phase,
  projectId,
  canManage,
  canReview,
  canOverride,
  defaultOpen,
  onSend,
  onRespond,
  onVoid,
  onReopen,
  onCloseByException,
  taskPhases,
  assignableUsers,
}: {
  phase: PhaseItem;
  projectId: string;
  canManage: boolean;
  canReview: boolean;
  canOverride: boolean;
  defaultOpen: boolean;
  onSend: (id: string, label: string, openPoints: number, missingApproval: boolean) => void;
  onRespond: (id: string, label: string, canFinishPhase: boolean) => void;
  onVoid: (id: string, label: string) => void;
  onReopen: (id: string, name: string) => void;
  onCloseByException: (id: string, name: string) => void;
  taskPhases: Array<{ key: string; name: string }>;
  assignableUsers: Array<{ id: string; display_name: string }>;
}) {
  const [open, setOpen] = useState(defaultOpen);

  // Phase-level server actions — one per action type; bound to this phase
  const [openIterState, openIterAction, openIterPending] = useActionState(
    openIterationAction.bind(null, projectId, phase.id),
    null as ActionResult<void> | null,
  );
  const [finishState, finishAction, finishPending] = useActionState(
    finishPhaseAction.bind(null, projectId, phase.id),
    null as ActionResult<void> | null,
  );
  const [startSupState, startSupAction, startSupPending] = useActionState(
    startSupervisionAction.bind(null, projectId, phase.id),
    null as ActionResult<void> | null,
  );
  const [finishSupState, finishSupAction, finishSupPending] = useActionState(
    finishSupervisionAction.bind(null, projectId, phase.id),
    null as ActionResult<void> | null,
  );

  const isDone = phase.state === "DONE";
  const isWaiting = phase.state === "WAITING_CLIENT";

  // Compute allowed phase-level actions (rounds)
  const hasOpenIter = phase.iterations.some(
    (i) => i.state === "DRAFT" || i.state === "SENT",
  );
  const latestNonVoided = phase.iterations.find((i) => i.state !== "VOIDED");
  const canFinish =
    phase.has_rounds &&
    !hasOpenIter &&
    latestNonVoided?.state === "APPROVED" &&
    !isDone;
  const canStartRound = phase.has_rounds && !hasOpenIter && !isDone && canManage;

  // Waiting age label
  let waitingAge: string | null = null;
  if (isWaiting) {
    const oldest = [...phase.iterations]
      .filter((i) => i.state === "SENT" && i.sent_at)
      .sort((a, b) => new Date(a.sent_at!).getTime() - new Date(b.sent_at!).getTime())[0];
    if (oldest?.sent_at) waitingAge = ageLabel(oldest.sent_at);
  }

  const stateText = PHASE_STATE_LABELS[phase.state] ?? phase.state;
  const phaseActionError =
    (openIterState?.ok === false ? openIterState.error.safeMessage : null) ??
    (finishState?.ok === false ? finishState.error.safeMessage : null) ??
    (startSupState?.ok === false ? startSupState.error.safeMessage : null) ??
    (finishSupState?.ok === false ? finishSupState.error.safeMessage : null);

  const contextualActions = (
    <div className="flex flex-wrap items-center gap-2 border-t border-line pt-2">
      {!phase.has_rounds && phase.state === "NOT_STARTED" && canReview && (
        <form action={startSupAction}>
          <Button type="submit" disabled={startSupPending} variant="secondary" size="sm">
            {startSupPending ? "Starting…" : "Start supervision"}
          </Button>
        </form>
      )}
      {!phase.has_rounds && phase.state === "IN_PROGRESS" && canReview && (
        <form action={finishSupAction}>
          <Button type="submit" disabled={finishSupPending} variant="secondary" size="sm">
            {finishSupPending ? "Completing…" : "Complete supervision"}
          </Button>
        </form>
      )}
      {canFinish && canReview && (
        <form action={finishAction}>
          <Button type="submit" disabled={finishPending} variant="secondary" size="sm">
            {finishPending ? "Finishing…" : "Finish phase"}
          </Button>
        </form>
      )}
      {!canFinish && canStartRound && (
        <form action={openIterAction}>
          <Button type="submit" disabled={openIterPending} variant="secondary" size="sm">
            {openIterPending ? "Starting…" : "Start round"}
          </Button>
        </form>
      )}
    </div>
  );

  return (
    <Surface className="overflow-hidden">
      {/* Header row */}
      <div
        className={`flex items-center gap-2 px-4 py-3 ${
          isDone
            ? "bg-surface-muted"
            : "bg-surface"
        }`}
      >
        <button
          type="button"
          aria-expanded={open}
          onClick={() => setOpen((value) => !value)}
          className="flex min-w-0 flex-1 items-center gap-2 text-left select-none"
        >
          <span className="shrink-0 text-ink-tertiary">
            {open ? <ChevronDown size={14} /> : <ChevronRight size={14} />}
          </span>
          <span
            className={`min-w-0 flex-1 text-sm font-medium ${
              isDone ? "text-ink-tertiary" : "text-ink"
            }`}
          >
            {phase.name}
          </span>
        </button>

        {/* Right side: state label + optional action button */}
        <div className="flex items-center gap-2.5 shrink-0">
          <span
            className={`text-xs ${
              isWaiting
                ? "text-ink-secondary font-medium"
                : "text-ink-tertiary"
            }`}
          >
            {waitingAge ? `${stateText} · ${waitingAge}` : stateText}
          </span>

          {/* Phase-level ⋯ menu — reopen (DONE), close by exception (active) */}
          {(canReview && isDone) || (canOverride && !isDone && !hasOpenIter) ? (
            <RowActionMenu
              label={`Actions for ${phase.name} phase`}
              items={[
                ...(isDone
                  ? [
                      {
                        label: "Reopen",
                        onSelect: () => onReopen(phase.id, phase.name),
                      } as const,
                    ]
                  : []),
                ...(canOverride && !isDone && !hasOpenIter
                  ? [
                      {
                        label: "Close as exception",
                        danger: true,
                        onSelect: () => onCloseByException(phase.id, phase.name),
                      } as const,
                    ]
                  : []),
              ]}
            />
          ) : null}
        </div>
      </div>

      {/* Phase action error */}
      {phaseActionError && (
        <div className="px-4 py-1.5 border-t border-line bg-surface-muted">
          <InlineError>{phaseActionError}</InlineError>
        </div>
      )}

      {/* Body — round-bearing */}
      {open && phase.has_rounds && (
        <div className="border-t border-line px-4 py-2.5 flex flex-col gap-1.5 bg-surface">
          <PhaseDeliverableBlock phase={phase} projectId={projectId} canManage={canManage} />
          {contextualActions}
          <GeneralTaskBlock
            projectId={projectId}
            tasks={phase.tasks}
            canManage={canManage}
            phases={taskPhases}
            title={`TODO ${phase.name}`}
            phaseScope={phase.key}
            users={assignableUsers}
          />
          {phase.iterations.length === 0 ? (
            <p className="text-sm text-ink-tertiary py-0.5">
              No rounds yet.
              {canManage && !isDone ? " Use 'Start round' to begin." : ""}
            </p>
          ) : (
            phase.iterations.map((iter) => (
              <IterationBlock
                key={iter.id}
                iteration={iter}
                phase={phase}
                projectId={projectId}
                canReview={canReview}
                onSend={onSend}
                onRespond={onRespond}
                onVoid={onVoid}
              />
            ))
          )}
        </div>
      )}

      {/* Body — supervision */}
      {open && !phase.has_rounds && (
        <div className="border-t border-line px-4 py-3 bg-surface">
          <PhaseDeliverableBlock phase={phase} projectId={projectId} canManage={canManage} />
          {contextualActions}
          <GeneralTaskBlock
            projectId={projectId}
            tasks={phase.tasks}
            canManage={canManage}
            phases={taskPhases}
            title={`TODO ${phase.name}`}
            phaseScope={phase.key}
            users={assignableUsers}
          />
          <p className="text-sm text-ink-tertiary">
            {phase.state === "NOT_STARTED"
              ? "Supervision has not started."
              : phase.state === "IN_PROGRESS"
              ? "Supervision is in progress."
              : "Supervision is complete."}
          </p>
        </div>
      )}
    </Surface>
  );
}

// ── Phase Section (exported) ──────────────────────────────────────────────────

export function PhaseSection({
  phases,
  projectId,
  canManage,
  canReview,
  canOverride,
  taskPhases,
  assignableUsers,
}: {
  phases: PhaseItem[];
  projectId: string;
  canManage: boolean;
  canReview: boolean;
  canOverride: boolean;
  taskPhases: Array<{ key: string; name: string }>;
  assignableUsers: Array<{ id: string; display_name: string }>;
}) {
  const [filter, setFilter] = useState<string | null>(null);
  const [sendDialog, setSendDialog] = useState<{
    id: string;
    label: string;
    openPoints: number;
    missingApproval: boolean;
  } | null>(null);
  const [respondDialog, setRespondDialog] = useState<{
    id: string;
    label: string;
    canFinishPhase: boolean;
  } | null>(null);
  const [voidDialog, setVoidDialog] = useState<{
    id: string;
    label: string;
  } | null>(null);
  const [reopenDialog, setReopenDialog] = useState<{
    id: string;
    name: string;
    hasRounds: boolean;
  } | null>(null);
  const [closeByExDialog, setCloseByExDialog] = useState<{
    id: string;
    name: string;
  } | null>(null);

  const filtered = filter ? phases.filter((p) => p.id === filter) : phases;

  return (
    <div className="flex flex-col gap-3">
      {/* Filter chips — only when multiple phases */}
      {phases.length > 1 && (
        <div className="flex flex-wrap gap-1.5">
          <FilterChip
            selected={filter === null}
            onClick={() => setFilter(null)}
            >
            All
          </FilterChip>
          {phases.map((phase) => (
            <FilterChip
              key={phase.id}
              selected={filter === phase.id}
              onClick={() => setFilter(phase.id)}
              >
              {phase.name}
            </FilterChip>
          ))}
        </div>
      )}

      {/* Phase blocks */}
      <div className="flex flex-col gap-2">
        {filtered.map((phase) => (
          <PhaseBlock
            key={phase.id}
            phase={phase}
            projectId={projectId}
            canManage={canManage}
            canReview={canReview}
            canOverride={canOverride}
            defaultOpen={
              phase.state === "IN_PROGRESS" || phase.state === "WAITING_CLIENT"
            }
            onSend={(id, label, openPoints, missingApproval) =>
              setSendDialog({ id, label, openPoints, missingApproval })
            }
            onRespond={(id, label, canFinishPhase) =>
              setRespondDialog({ id, label, canFinishPhase })
            }
            onVoid={(id, label) => setVoidDialog({ id, label })}
            onReopen={(id, name) => {
              const phase = phases.find((candidate) => candidate.id === id);
              if (phase) setReopenDialog({ id, name, hasRounds: phase.has_rounds });
            }}
            onCloseByException={(id, name) => setCloseByExDialog({ id, name })}
            taskPhases={taskPhases}
            assignableUsers={assignableUsers}
          />
        ))}
      </div>

      {/* Dialogs */}
      {sendDialog && (
        <SendDialog
          key={sendDialog.id}
          iterationId={sendDialog.id}
          label={sendDialog.label}
          projectId={projectId}
          openPoints={sendDialog.openPoints}
          missingApproval={sendDialog.missingApproval}
          onClose={() => setSendDialog(null)}
        />
      )}
      {respondDialog && (
        <ResponseDialog
          key={respondDialog.id}
          iterationId={respondDialog.id}
          label={respondDialog.label}
          projectId={projectId}
          canFinishPhase={respondDialog.canFinishPhase}
          onClose={() => setRespondDialog(null)}
        />
      )}
      {voidDialog && (
        <VoidDialog
          key={voidDialog.id}
          iterationId={voidDialog.id}
          label={voidDialog.label}
          projectId={projectId}
          onClose={() => setVoidDialog(null)}
        />
      )}
      {reopenDialog && (
        <ReopenPhaseDialog
          key={reopenDialog.id}
          phaseId={reopenDialog.id}
          phaseName={reopenDialog.name}
          hasRounds={reopenDialog.hasRounds}
          projectId={projectId}
          onClose={() => setReopenDialog(null)}
        />
      )}
      {closeByExDialog && (
        <CloseByExceptionDialog
          key={closeByExDialog.id}
          phaseId={closeByExDialog.id}
          phaseName={closeByExDialog.name}
          projectId={projectId}
          onClose={() => setCloseByExDialog(null)}
        />
      )}
    </div>
  );
}
